-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/courses/*.json — do not hand-edit.
--
-- Platform courses batch C: 2 courses.
--
-- Confidence is noted per course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Holes are HIGH or MEDIUM only. A wrong stroke index mis-hands shots on
-- every round of this course, forever, and no screen ever says so. Tee
-- ratings may be lower: a wrong slope is a fraction of a shot, and a
-- scorecard photo corrects it.
--
-- card_verified stays false on every row. Where there are holes they make
-- the course playable (`hasCard` is holes.length > 0) and the badge says,
-- honestly, that no photograph has confirmed them — a later photo takes the
-- diff path, because handleCreate refuses a course that already has holes.
-- Where there are none, the course is searchable and carries its weather,
-- scoring is gated, and the first photo takes handleCreate's create path
-- and writes the card.
--
-- Replay-safe: every insert is ON CONFLICT DO NOTHING and nothing here
-- deletes. Migration 008 cleared its tees first; that is no longer safe,
-- because round_handicaps.tee_id is ON DELETE RESTRICT and a tee somebody
-- has played off cannot be removed.
-- ============================================================

BEGIN;

INSERT INTO courses
  (trip_id, name, slug, location, county, website, latitude, longitude,
   geocoded_at, card_verified, ladies_data_verified, ladies_data_note)
VALUES
  -- https://www.google.com/maps/place/55.1638,-6.7741
  (NULL, 'Castlerock Golf Club -- Mussenden', 'castlerock-mussenden', 'Castlerock, Derry, Northern Ireland', 'Derry', 'https://www.castlerockgc.co.uk/', 55.1638, -6.7741, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.0601,-7.2130
  (NULL, 'The Heath Golf Club',               'the-heath',            'The Heath, Laois, Ireland',           'Laois', 'https://www.theheathgc.ie/',      53.0601,  -7.213, now(), false, true,  NULL)
ON CONFLICT DO NOTHING;

-- ── Castlerock Golf Club -- Mussenden (par 73 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/18824-castlerock-golf-club-mussenden, https://www.golfify.io/courses/castlerock-golf-club-mussenden
-- Note: Ladies scorecard (per-hole par and stroke index) not published; the R&A rates a par-75 ladies tee, but with no hole-by-hole ladies card the men's numbers are used for everyone.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  9::int, NULL::int, NULL::int),
  ( 2,      4,       5,      NULL,      NULL),
  ( 3,      5,      13,      NULL,      NULL),
  ( 4,      3,      11,      NULL,      NULL),
  ( 5,      5,      15,      NULL,      NULL),
  ( 6,      4,       7,      NULL,      NULL),
  ( 7,      4,       1,      NULL,      NULL),
  ( 8,      4,       3,      NULL,      NULL),
  ( 9,      3,      17,      NULL,      NULL),
  (10,      4,       4,      NULL,      NULL),
  (11,      5,      16,      NULL,      NULL),
  (12,      4,       2,      NULL,      NULL),
  (13,      4,      14,      NULL,      NULL),
  (14,      3,       8,      NULL,      NULL),
  (15,      5,       6,      NULL,      NULL),
  (16,      3,      18,      NULL,      NULL),
  (17,      5,      12,      NULL,      NULL),
  (18,      4,      10,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'castlerock-mussenden' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── The Heath Golf Club (par 71 men / 72 ladies) ──
-- HOLES MEDIUM: https://www.theheathgc.ie/course-details, https://www.hole19golf.com/courses/the-heath-golf-club, https://golftraxx.com/scorecard?course_name=The+Heath+Golf+Club&fulladdress=The+Heath+Portlaoise+IR&zipcode=LAOIS&static=true
-- Note: Ladies play the 13th as a par 5.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 14::int, 5::int, 10::int),
  ( 2,      3,      12,      3,      14),
  ( 3,      4,       2,      4,       2),
  ( 4,      5,      10,      5,      12),
  ( 5,      4,      18,      4,       6),
  ( 6,      4,       6,      4,      16),
  ( 7,      4,       8,      4,       8),
  ( 8,      4,       4,      4,       4),
  ( 9,      3,      16,      3,      18),
  (10,      4,       7,      4,       1),
  (11,      3,      15,      3,      17),
  (12,      4,      17,      4,      13),
  (13,      4,       1,      5,      15),
  (14,      4,      11,      4,       9),
  (15,      4,       3,      4,       3),
  (16,      5,       9,      5,       7),
  (17,      3,      13,      3,      11),
  (18,      4,       5,      4,       5)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'the-heath' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO tees (course_id, name, gender, par, course_rating, slope)
SELECT c.id, spec.tee_name, spec.gender, spec.par::integer,
       spec.course_rating::numeric, spec.slope::integer
FROM (VALUES
  -- ── Castlerock Golf Club -- Mussenden ──
  -- TEES MEDIUM: https://ncrdb.usga.org/courseTeeInfo?CourseID=22949, https://www.golfify.io/courses/castlerock-golf-club-mussenden
  ('castlerock-mussenden', 'Blue',   'M', 73, 73.4, 131),
  ('castlerock-mussenden', 'White',  'M', 73, 72.0, 128),
  ('castlerock-mussenden', 'Red',    'M', 73, 68.9, 117),

  -- ── The Heath Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20801-the-heath-golf-club, https://www.golfnow.co.uk/courses/-238-the-heath-golf-club-details, https://www.theheathgc.ie/course-and-slope-rating
  ('the-heath',            'Blue',   'M', 71, 72.6, 126),
  ('the-heath',            'White',  'M', 71, 71.3, 125),
  ('the-heath',            'Yellow', 'M', 71, 70.3, 123),
  ('the-heath',            'Red',    'F', 72, 70.7, 112)
) AS spec(slug, tee_name, gender, par, course_rating, slope)
JOIN courses c ON c.slug = spec.slug AND c.trip_id IS NULL
ON CONFLICT ON CONSTRAINT uq_tees_course_name_gender DO NOTHING;

COMMIT;
