-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/courses/*.json — do not hand-edit.
--
-- Platform courses batch F: 4 courses, 2 of them with no card yet.
--
-- Confidence is noted per course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Holes are HIGH or MEDIUM only. A wrong stroke index mis-hands shots on
-- every round of this course, forever, and no screen ever says so. Tee
-- ratings may be lower: a wrong slope is a fraction of a shot, and a
-- scorecard photo corrects it.
--
-- card_verified stays false on every row. Where there are holes they make
-- the course playable (`hasCard` is holes.length > 0) and the badge says,
-- honestly, that no photograph has confirmed them — a later photo takes the
-- diff path, because handleCreate refuses a course that already has holes.
-- Where there are none, the course is searchable and carries its weather,
-- scoring is gated, and the first photo takes handleCreate's create path
-- and writes the card.
--
-- A course here may also have no tees. Irish clubs print SSS, not a slope,
-- and without a rating and a slope together there is no tee row to write.
-- It is the same gate from the other side — canStart needs a tee for every
-- player — so the course is findable and cannot be started, and admin badges
-- it "Awaiting ratings" rather than "Awaiting photo", because a photograph
-- is not what it is short of. Those arrive later through data/course-tees/.
--
-- Replay-safe: every insert is ON CONFLICT DO NOTHING and nothing here
-- deletes. Migration 008 cleared its tees first; that is no longer safe,
-- because round_handicaps.tee_id is ON DELETE RESTRICT and a tee somebody
-- has played off cannot be removed.
-- ============================================================

BEGIN;

INSERT INTO courses
  (trip_id, name, slug, location, county, website, latitude, longitude,
   geocoded_at, card_verified, ladies_data_verified, ladies_data_note)
VALUES
  (NULL, 'Bunclody Golf and Fishing Club', 'bunclody',             'Bunclody, Wexford, Ireland',   'Wexford', 'https://bunclodygfc.ie/',              52.6566, -6.6567, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  (NULL, 'Esker Hills Golf Club',          'esker-hills',          'Tullamore, Offaly, Ireland',   'Offaly',  'https://www.eskerhillsgolf.com/',      53.3136, -7.5575, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  (NULL, 'Luttrellstown Castle Golf Club', 'luttrellstown-castle', 'Clonsilla, Dublin, Ireland',   'Dublin',  'https://www.luttrellstowncastle.com/', 53.3856, -6.4044, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  (NULL, 'The Castle Golf Club',           'the-castle',           'Rathfarnham, Dublin, Ireland', 'Dublin',  'https://castlegc.ie/',                 53.2991, -6.2774, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo')
ON CONFLICT DO NOTHING;

-- ── Bunclody Golf and Fishing Club (no scorecard) ──
-- HOLES NONE: Eighteen holes of about 7,000 yards, known for a par-3 14th played down a quarry face. No per-hole card and no course rating or slope published on the club site, and nothing corroborated elsewhere. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Esker Hills Golf Club (par 71 men) ──
-- HOLES HIGH: https://www.eskerhillsgolf.com/scorecard.html
-- Note: Men's card from the club's own scorecard page. The club publishes SSS, not a USGA course rating and slope, so no tee can be written yet — the ratings come later from a handicap table or Golf Ireland. A ladies card is published (par 72) but was not transcribed.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 17::int, NULL::int, NULL::int),
  ( 2,      4,      11,      NULL,      NULL),
  ( 3,      4,       1,      NULL,      NULL),
  ( 4,      4,       5,      NULL,      NULL),
  ( 5,      3,      15,      NULL,      NULL),
  ( 6,      5,       9,      NULL,      NULL),
  ( 7,      4,       3,      NULL,      NULL),
  ( 8,      4,      13,      NULL,      NULL),
  ( 9,      3,       7,      NULL,      NULL),
  (10,      4,      18,      NULL,      NULL),
  (11,      4,       4,      NULL,      NULL),
  (12,      4,       6,      NULL,      NULL),
  (13,      3,      14,      NULL,      NULL),
  (14,      4,      10,      NULL,      NULL),
  (15,      3,       8,      NULL,      NULL),
  (16,      5,      16,      NULL,      NULL),
  (17,      4,       2,      NULL,      NULL),
  (18,      4,      12,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'esker-hills' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Luttrellstown Castle Golf Club (par 72 men) ──
-- HOLES HIGH: https://www.luttrellstowncastle.com/
-- Note: Men's par and stroke index and the ladies stroke index from the club's official scorecard PDF; the exact PDF path was not recorded, so the source is the club site. The ladies card gives par 72 as a total only, so no per-hole ladies par is carried. The club publishes SSS (Blue 76 / White 74 / Green 72 / Red 73) and no slope, so no tee can be written yet.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  6::int, NULL::int,  7::int),
  ( 2,      5,      12,      NULL,       5),
  ( 3,      4,       8,      NULL,       9),
  ( 4,      3,      18,      NULL,      15),
  ( 5,      4,       2,      NULL,       1),
  ( 6,      3,      10,      NULL,      17),
  ( 7,      4,       4,      NULL,       3),
  ( 8,      5,      16,      NULL,      13),
  ( 9,      4,      14,      NULL,      11),
  (10,      4,       7,      NULL,       2),
  (11,      4,      13,      NULL,      18),
  (12,      5,      15,      NULL,      10),
  (13,      3,       9,      NULL,      16),
  (14,      4,       3,      NULL,      12),
  (15,      3,      17,      NULL,      14),
  (16,      4,      11,      NULL,       8),
  (17,      4,       1,      NULL,       6),
  (18,      5,       5,      NULL,       4)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'luttrellstown-castle' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── The Castle Golf Club (no scorecard) ──
-- HOLES NONE: Harry Colt parkland at Rathfarnham. The club site is video-led and publishes neither a per-hole scorecard nor a course rating and slope; no corroborated card was found elsewhere. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

COMMIT;

-- ── Did it land? ──────────────────────────────────────────
-- This runs itself. Every course below should come back with its holes and
-- its tees; /admin/courses says the same thing with badges. Re-pasting the
-- whole file is safe and asks the question again — every write above either
-- skips or rewrites the same values, so a second run leaves the database
-- where the first one left it.
select c.slug, c.name, c.county, c.card_verified,
       (select count(*) from holes h where h.course_id = c.id) as holes,
       (select count(*) from tees  t where t.course_id = c.id) as tees
from courses c
where c.trip_id is null
  and c.slug in ('bunclody', 'esker-hills', 'luttrellstown-castle', 'the-castle')
order by c.name;
