-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/courses/*.json — do not hand-edit.
--
-- Platform courses batch H: 1 course, 1 of them with no card yet.
--
-- Confidence is noted per course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Holes are HIGH or MEDIUM only. A wrong stroke index mis-hands shots on
-- every round of this course, forever, and no screen ever says so. Tee
-- ratings may be lower: a wrong slope is a fraction of a shot, and a
-- scorecard photo corrects it.
--
-- card_verified stays false on every row. Where there are holes they make
-- the course playable (`hasCard` is holes.length > 0) and the badge says,
-- honestly, that no photograph has confirmed them — a later photo takes the
-- diff path, because handleCreate refuses a course that already has holes.
-- Where there are none, the course is searchable and carries its weather,
-- scoring is gated, and the first photo takes handleCreate's create path
-- and writes the card.
--
-- A course here may also have no tees. Irish clubs print SSS, not a slope,
-- and without a rating and a slope together there is no tee row to write.
-- It is the same gate from the other side — canStart needs a tee for every
-- player — so the course is findable and cannot be started, and admin badges
-- it "Awaiting ratings" rather than "Awaiting photo", because a photograph
-- is not what it is short of. Those arrive later through data/course-tees/.
--
-- Replay-safe: every insert is ON CONFLICT DO NOTHING and nothing here
-- deletes. Migration 008 cleared its tees first; that is no longer safe,
-- because round_handicaps.tee_id is ON DELETE RESTRICT and a tee somebody
-- has played off cannot be removed.
-- ============================================================

BEGIN;

INSERT INTO courses
  (trip_id, name, slug, location, county, website, latitude, longitude,
   geocoded_at, card_verified, ladies_data_verified, ladies_data_note)
VALUES
  (NULL, 'Carne Golf Links -- Hackett Course', 'carne-hackett', 'Belmullet, Mayo, Ireland', 'Mayo', 'https://carnegolflinks.com/', 54.2237, -10.0338, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo')
ON CONFLICT DO NOTHING;

-- ── Carne Golf Links -- Hackett Course (no scorecard) ──
-- HOLES NONE: The original Eddie Hackett 18 at Carne, beside the Wild Atlantic Dunes composite. No card sourced — the eighteen arrive with the first scorecard photo. Tees are official WHS ratings from the Golf Ireland app (listed there as Belmullet-Hackett), Aug 2026.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

INSERT INTO tees (course_id, name, gender, par, course_rating, slope)
SELECT c.id, spec.tee_name, spec.gender, spec.par::integer,
       spec.course_rating::numeric, spec.slope::integer
FROM (VALUES
  -- ── Carne Golf Links -- Hackett Course ──
  -- TEES HIGH: https://www.golfireland.ie/
  ('carne-hackett', 'Blue',   'M', 72, 72.6, 124),
  ('carne-hackett', 'White',  'M', 72, 71.2, 120),
  ('carne-hackett', 'Yellow', 'M', 72, 68.4, 116),
  ('carne-hackett', 'Red',    'F', 73, 72.0, 121)
) AS spec(slug, tee_name, gender, par, course_rating, slope)
JOIN courses c ON c.slug = spec.slug AND c.trip_id IS NULL
ON CONFLICT ON CONSTRAINT uq_tees_course_name_gender DO NOTHING;

COMMIT;

-- ── Did it land? ──────────────────────────────────────────
-- This runs itself. Every course below should come back with its holes and
-- its tees; /admin/courses says the same thing with badges. Re-pasting the
-- whole file is safe and asks the question again — every write above either
-- skips or rewrites the same values, so a second run leaves the database
-- where the first one left it.
select c.slug, c.name, c.county, c.card_verified,
       (select count(*) from holes h where h.course_id = c.id) as holes,
       (select count(*) from tees  t where t.course_id = c.id) as tees
from courses c
where c.trip_id is null
  and c.slug in ('carne-hackett')
order by c.name;
