-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/courses/*.json — do not hand-edit.
--
-- Platform courses batch G: 19 courses, 15 of them with no card yet.
--
-- Confidence is noted per course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Holes are HIGH or MEDIUM only. A wrong stroke index mis-hands shots on
-- every round of this course, forever, and no screen ever says so. Tee
-- ratings may be lower: a wrong slope is a fraction of a shot, and a
-- scorecard photo corrects it.
--
-- card_verified stays false on every row. Where there are holes they make
-- the course playable (`hasCard` is holes.length > 0) and the badge says,
-- honestly, that no photograph has confirmed them — a later photo takes the
-- diff path, because handleCreate refuses a course that already has holes.
-- Where there are none, the course is searchable and carries its weather,
-- scoring is gated, and the first photo takes handleCreate's create path
-- and writes the card.
--
-- A course here may also have no tees. Irish clubs print SSS, not a slope,
-- and without a rating and a slope together there is no tee row to write.
-- It is the same gate from the other side — canStart needs a tee for every
-- player — so the course is findable and cannot be started, and admin badges
-- it "Awaiting ratings" rather than "Awaiting photo", because a photograph
-- is not what it is short of. Those arrive later through data/course-tees/.
--
-- Replay-safe: every insert is ON CONFLICT DO NOTHING and nothing here
-- deletes. Migration 008 cleared its tees first; that is no longer safe,
-- because round_handicaps.tee_id is ON DELETE RESTRICT and a tee somebody
-- has played off cannot be removed.
-- ============================================================

BEGIN;

INSERT INTO courses
  (trip_id, name, slug, location, county, website, latitude, longitude,
   geocoded_at, card_verified, ladies_data_verified, ladies_data_note)
VALUES
  -- https://www.google.com/maps/place/52.7866,-6.1475
  (NULL, 'Arklow Golf Links',                             'arklow',                     'Arklow, Wicklow, Ireland',            'Wicklow',   'https://www.arklowgolflinks.com/',     52.7866,  -6.1475, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/54.5617,-5.9129
  (NULL, 'Belvoir Park Golf Club',                        'belvoir-park',               'Belfast, Down, Northern Ireland',     'Down',      'https://www.belvoirparkgolfclub.com/', 54.5617,  -5.9129, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/52.0827,-9.9255
  (NULL, 'Dooks Golf Club',                               'dooks',                      'Glenbeigh, Kerry, Ireland',           'Kerry',     'https://www.dooks.com/',               52.0827,  -9.9255, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.2063,-6.1541
  (NULL, 'Dun Laoghaire Golf Club',                       'dun-laoghaire',              'Enniskerry, Dublin, Ireland',         'Dublin',    'https://www.dunlaoghairegolfclub.ie/', 53.2063,  -6.1541, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.9931,-7.3985
  (NULL, 'Farnham Estate Golf Club',                      'farnham-estate',             'Cavan, Cavan, Ireland',               'Cavan',     'https://www.farnhamestate.ie/',        53.9931,  -7.3985, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/54.8551,-6.3126
  (NULL, 'Galgorm Castle Golf Club',                      'galgorm-castle',             'Ballymena, Antrim, Northern Ireland', 'Antrim',    'https://www.galgormcastle.com/',       54.8551,  -6.3126, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.2498,-8.9743
  (NULL, 'Galway Bay Golf Resort',                        'galway-bay',                 'Oranmore, Galway, Ireland',           'Galway',    'https://www.galwaybaygolfresort.com/', 53.2498,  -8.9743, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.2597,-9.0949
  (NULL, 'Galway Golf Club',                              'galway-golf-club',           'Salthill, Galway, Ireland',           'Galway',    'https://www.galwaygolf.com/',          53.2597,  -9.0949, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.1285,-7.1541
  (NULL, 'The Heritage Golf Resort',                      'heritage-killenard',         'Killenard, Laois, Ireland',           'Laois',     'https://www.theheritage.com/',         53.1285,  -7.1541, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/51.8181,-10.1669
  (NULL, 'Hog''s Head Golf Club',                         'hogs-head',                  'Waterville, Kerry, Ireland',          'Kerry',     'https://hogsheadgolfclub.com/',        51.8181, -10.1669, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/52.6721,-7.2439
  (NULL, 'Kilkenny Golf Club',                            'kilkenny',                   'Kilkenny, Kilkenny, Ireland',         'Kilkenny',  'https://www.kilkennygolfclub.com/',    52.6721,  -7.2439, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/54.4368,-5.4729
  (NULL, 'Kirkistown Castle Golf Club',                   'kirkistown-castle',          'Cloughey, Down, Northern Ireland',    'Down',      'https://kcgc.golf/',                   54.4368,  -5.4729, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/52.7912,-6.7295
  (NULL, 'Mount Wolseley Golf Club',                      'mount-wolseley',             'Tullow, Carlow, Ireland',             'Carlow',    'https://www.mountwolseley.ie/',        52.7912,  -6.7295, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.4226,-6.9273
  (NULL, 'Moyvalley Golf Club',                           'moyvalley',                  'Moyvalley, Kildare, Ireland',         'Kildare',   'https://www.moyvalley.com/',           53.4226,  -6.9273, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.3885,-7.4310
  (NULL, 'New Forest Golf Club',                          'new-forest',                 'Tyrrellspass, Westmeath, Ireland',    'Westmeath', 'https://www.newforestgolf.com/',       53.3885,   -7.431, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.2514,-6.6261
  (NULL, 'Palmerstown House Estate',                      'palmerstown-house',          'Johnstown, Kildare, Ireland',         'Kildare',   'https://www.palmerstownhouse.ie/',     53.2514,  -6.6261, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/53.0911,-8.2558
  (NULL, 'Portumna Golf Club',                            'portumna',                   'Portumna, Galway, Ireland',           'Galway',    'https://portumnagolfclub.ie/',         53.0911,  -8.2558, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.2268,-5.8677
  (NULL, 'Royal County Down Golf Club -- Annesley Links', 'royal-county-down-annesley', 'Newcastle, Down, Northern Ireland',   'Down',      'https://www.royalcountydown.org/',     54.2268,  -5.8677, now(), false, false, 'No scorecard published — the card arrives with the first scorecard photo'),
  -- https://www.google.com/maps/place/52.1573,-7.1706
  (NULL, 'Tramore Golf Club -- Old Course',               'tramore',                    'Tramore, Waterford, Ireland',         'Waterford', 'https://tramoregolfclub.com/',         52.1573,  -7.1706, now(), false, true,  NULL)
ON CONFLICT DO NOTHING;

-- ── Arklow Golf Links (no scorecard) ──
-- HOLES NONE: Par 70 men / 72 ladies. The club publishes its scorecard only as an image (/wp-content/uploads/sites/7570/2019/06/Folded-Score-Card-2018-FINAL-Print-2.jpg), which the research tools cannot read. Aggregators agree on the par hole-by-hole but their stroke-index columns disagree on most holes (golfsherpa vs 18birdies), so no trustworthy stroke index could be transcribed without picking a winner. Lands cardless; the first scorecard photo settles the card. No USGA course rating or slope published either.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Belvoir Park Golf Club (no scorecard) ──
-- HOLES NONE: Par 71. The par is solid and 14 of 18 stroke indices agree across sources, but holes 11 and 18 are dead 2-2 ties between sources and cannot be resolved without the club's own card. No stroke index could be transcribed without guessing those, so it lands cardless; the first scorecard photo settles it. No USGA course rating or slope published.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Dooks Golf Club (no scorecard) ──
-- HOLES NONE: Par 71. The par is solid but the stroke index genuinely conflicts between sources: the club site (dooks.com) and the shared aggregator feed (18birdies/golfsherpa) disagree on most holes, and the course is not in the USGA NCRDB. No stroke index could be transcribed without picking a winner, so it lands cardless; the first scorecard photo settles it. No USGA course rating or slope published.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Dun Laoghaire Golf Club (no scorecard) ──
-- HOLES NONE: A 27-hole facility at Ballyman Road, Enniskerry (Upper, Middle and Lower nines, each par 36) with no canonically published combined eighteen, so which holes make up the played card is not invented here. County is the clubhouse townland (Ballyman, Co. Dublin); the course straddles the Dublin/Wicklow border and the postal town Enniskerry is in Wicklow. Lands cardless with coordinates and weather; a photograph of the card handed out at the desk settles which eighteen it is. If a second composite is later needed it is a second course row, named 'Dun Laoghaire Golf Club -- Composite 18 No 2', not a rename.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Farnham Estate Golf Club (no scorecard) ──
-- HOLES NONE: Jeff Howes parkland in the Farnham estate, about 4 km west of Cavan town. The resort site published no reachable hole-by-hole scorecard and nothing was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Galgorm Castle Golf Club (no scorecard) ──
-- HOLES NONE: Par 72. The par is solid but two different stroke-index allocations circulate (Hole19 vs 18birdies) and disagree, so no stroke index could be transcribed without picking a winner. Uncorroborated tee ratings exist on 18birdies but are left out rather than graded LOW. Lands cardless; the first scorecard photo settles the card.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Galway Bay Golf Resort (no scorecard) ──
-- HOLES NONE: Christy O'Connor Jnr parkland on the Renville peninsula, Oranmore (par 72, about 7,300 yards). The resort site published no reachable hole-by-hole scorecard and nothing was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Galway Golf Club (no scorecard) ──
-- HOLES NONE: Alister MacKenzie parkland-links at Blackrock, Salthill (1926). The club site returned no reachable hole-by-hole scorecard and nothing was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── The Heritage Golf Resort (no scorecard) ──
-- HOLES NONE: Seve Ballesteros and Jeff Howes parkland at Killenard (par 72, about 7,300 yards). The resort site published no reachable hole-by-hole scorecard and nothing was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Hog's Head Golf Club (no scorecard) ──
-- HOLES NONE: Private Robert Trent Jones Jr. links at Ballybrack, near Waterville (about 7,150 yards). The club course page lists hole names, pars and yardages but no stroke index, so no card could be transcribed; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Kilkenny Golf Club (par 71 men / 73 ladies) ──
-- HOLES HIGH: https://www.kilkennygolfclub.com/the-course/scorecard/
-- Note: Men's (par 71) and ladies' (par 73) par and stroke index from the club's own scorecard page; both cards are clean 1-18 permutations. The club publishes SSS (White 71 / Green 70 / Ladies 73) and no USGA course rating or slope, so no tee can be written yet — ratings arrive later through data/course-tees/.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  4::int, 5::int, 17::int),
  ( 2,      4,       8,      4,       7),
  ( 3,      4,       2,      4,       9),
  ( 4,      4,      16,      4,       5),
  ( 5,      4,      18,      4,      13),
  ( 6,      3,      14,      3,      15),
  ( 7,      4,      10,      4,       3),
  ( 8,      4,       6,      4,      11),
  ( 9,      5,      12,      5,       1),
  (10,      3,       7,      3,      12),
  (11,      4,       1,      5,      14),
  (12,      5,      13,      5,       8),
  (13,      4,       5,      4,       6),
  (14,      5,      17,      5,       2),
  (15,      3,       9,      3,      18),
  (16,      4,       3,      4,       4),
  (17,      3,      11,      3,      16),
  (18,      4,      15,      4,      10)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'kilkenny' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Kirkistown Castle Golf Club (no scorecard) ──
-- HOLES NONE: Two whole scorecards circulate and disagree: one gives par 70 with hole 10 a par 5, the other par 69 with hole 10 a par 4, and their stroke-index columns differ on 13 of 18 holes. The published tee ratings conflict too (White 70.0/126 vs 70.3/118). Nothing could be transcribed without choosing between them, so it lands cardless; the first scorecard photo settles it.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Mount Wolseley Golf Club (par 72 men) ──
-- HOLES HIGH: https://www.mountwolseley.ie/wp-content/uploads/pdf/golf-score-cards.pdf
-- Note: Men's par and stroke index from the club's own scorecard PDF (/wp-content/uploads/pdf/golf-score-cards.pdf). A ladies card is published (par 74) but was not transcribed, so no per-hole ladies data is carried. The club publishes SSS (Blue 75 / White 73 / Yellow 71 / Red 73) and no USGA course rating or slope, so no tee can be written yet — ratings arrive later through data/course-tees/.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  5::int, NULL::int, NULL::int),
  ( 2,      4,       3,      NULL,      NULL),
  ( 3,      4,       1,      NULL,      NULL),
  ( 4,      4,      11,      NULL,      NULL),
  ( 5,      5,      13,      NULL,      NULL),
  ( 6,      3,       9,      NULL,      NULL),
  ( 7,      5,      15,      NULL,      NULL),
  ( 8,      4,       7,      NULL,      NULL),
  ( 9,      3,      17,      NULL,      NULL),
  (10,      5,      14,      NULL,      NULL),
  (11,      3,       4,      NULL,      NULL),
  (12,      5,      18,      NULL,      NULL),
  (13,      4,       8,      NULL,      NULL),
  (14,      4,      16,      NULL,      NULL),
  (15,      4,       2,      NULL,      NULL),
  (16,      3,      10,      NULL,      NULL),
  (17,      4,      12,      NULL,      NULL),
  (18,      4,       6,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'mount-wolseley' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Moyvalley Golf Club (no scorecard) ──
-- HOLES NONE: Darren Clarke parkland at the Balyna estate, Moyvalley (par 72, four tees). The resort site published no reachable hole-by-hole scorecard and nothing was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── New Forest Golf Club (no scorecard) ──
-- HOLES NONE: Parkland at Higginstown, Tyrrellspass. The club site was intermittently unreachable and published no hole-by-hole scorecard; nothing was found corroborated elsewhere, and no USGA course rating or slope is published. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Palmerstown House Estate (no scorecard) ──
-- HOLES NONE: Christy O'Connor Jnr parkland at Johnstown, near Naas (par 72, about 7,400 yards). The estate site published no reachable hole-by-hole scorecard and nothing was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Portumna Golf Club (par 72 men) ──
-- HOLES HIGH: https://portumnagolfclub.ie/wp-content/uploads/2025/06/Portumna-Scorecard-1.pdf
-- Note: Men's par and stroke index from the club's own scorecard PDF (/wp-content/uploads/2025/06/Portumna-Scorecard-1.pdf); a clean 1-18 permutation. No hole-by-hole ladies card was transcribed. The club publishes SSS and no USGA course rating or slope, so no tee can be written yet — ratings arrive later through data/course-tees/.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  7::int, NULL::int, NULL::int),
  ( 2,      3,      17,      NULL,      NULL),
  ( 3,      4,       1,      NULL,      NULL),
  ( 4,      4,       5,      NULL,      NULL),
  ( 5,      3,       9,      NULL,      NULL),
  ( 6,      5,      11,      NULL,      NULL),
  ( 7,      4,       3,      NULL,      NULL),
  ( 8,      5,      15,      NULL,      NULL),
  ( 9,      4,      13,      NULL,      NULL),
  (10,      3,       6,      NULL,      NULL),
  (11,      4,      12,      NULL,      NULL),
  (12,      5,      18,      NULL,      NULL),
  (13,      4,      10,      NULL,      NULL),
  (14,      4,       4,      NULL,      NULL),
  (15,      4,      16,      NULL,      NULL),
  (16,      4,       8,      NULL,      NULL),
  (17,      5,       2,      NULL,      NULL),
  (18,      3,      14,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'portumna' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Royal County Down Golf Club -- Annesley Links (no scorecard) ──
-- HOLES NONE: The shorter second links at Royal County Down (Annesley), remodelled by Mackenzie & Ebert in 2015 and sharing the clubhouse with the Championship course. No hole-by-hole scorecard is published on the club site and none was found corroborated elsewhere; no USGA course rating or slope published either. Both arrive with the first scorecard photo.
-- The eighteen holes arrive with the first scorecard photo, through the
-- mode: 'create' path in app/api/card-check/apply. Scoring is gated until
-- then — hasCard is holes.length > 0 — and admin badges it "No scorecard",
-- which is cardState's `none`: the state where a photo is exactly the
-- answer, because it is what creates the eighteen.

-- ── Tramore Golf Club -- Old Course (par 72 men / 75 ladies) ──
-- HOLES HIGH: https://tramoregolfclub.com/the-club/scorecard/
-- Note: Men's (par 72) and ladies' (par 75) par and stroke index from the club's own scorecard; both cards are clean 1-18 permutations. The club publishes SSS and no USGA course rating or slope, so no tee can be written yet — ratings arrive later through data/course-tees/.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  8::int, 4::int, 10::int),
  ( 2,      5,      10,      5,       2),
  ( 3,      3,      12,      3,      18),
  ( 4,      4,       6,      4,       4),
  ( 5,      4,      14,      4,       8),
  ( 6,      3,      16,      3,      16),
  ( 7,      4,       4,      5,      14),
  ( 8,      4,       2,      5,      12),
  ( 9,      5,      18,      5,       6),
  (10,      3,       9,      3,      15),
  (11,      4,       7,      4,       5),
  (12,      4,      13,      4,      13),
  (13,      4,       3,      4,       1),
  (14,      4,       1,      5,      11),
  (15,      3,      17,      3,      17),
  (16,      5,      11,      5,       9),
  (17,      4,       5,      4,       3),
  (18,      5,      15,      5,       7)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'tramore' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

COMMIT;

-- ── Did it land? ──────────────────────────────────────────
-- This runs itself. Every course below should come back with its holes and
-- its tees; /admin/courses says the same thing with badges. Re-pasting the
-- whole file is safe and asks the question again — every write above either
-- skips or rewrites the same values, so a second run leaves the database
-- where the first one left it.
select c.slug, c.name, c.county, c.card_verified,
       (select count(*) from holes h where h.course_id = c.id) as holes,
       (select count(*) from tees  t where t.course_id = c.id) as tees
from courses c
where c.trip_id is null
  and c.slug in ('arklow', 'belvoir-park', 'dooks', 'dun-laoghaire', 'farnham-estate', 'galgorm-castle', 'galway-bay', 'galway-golf-club', 'heritage-killenard', 'hogs-head', 'kilkenny', 'kirkistown-castle', 'mount-wolseley', 'moyvalley', 'new-forest', 'palmerstown-house', 'portumna', 'royal-county-down-annesley', 'tramore')
order by c.name;
