-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/courses/*.json — do not hand-edit.
--
-- Platform courses batch D: 25 courses.
--
-- Confidence is noted per course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Holes are HIGH or MEDIUM only. A wrong stroke index mis-hands shots on
-- every round of this course, forever, and no screen ever says so. Tee
-- ratings may be lower: a wrong slope is a fraction of a shot, and a
-- scorecard photo corrects it.
--
-- card_verified stays false on every row. Where there are holes they make
-- the course playable (`hasCard` is holes.length > 0) and the badge says,
-- honestly, that no photograph has confirmed them — a later photo takes the
-- diff path, because handleCreate refuses a course that already has holes.
-- Where there are none, the course is searchable and carries its weather,
-- scoring is gated, and the first photo takes handleCreate's create path
-- and writes the card.
--
-- Replay-safe: every insert is ON CONFLICT DO NOTHING and nothing here
-- deletes. Migration 008 cleared its tees first; that is no longer safe,
-- because round_handicaps.tee_id is ON DELETE RESTRICT and a tee somebody
-- has played off cannot be removed.
-- ============================================================

BEGIN;

INSERT INTO courses
  (trip_id, name, slug, location, county, website, latitude, longitude,
   geocoded_at, card_verified, ladies_data_verified, ladies_data_note)
VALUES
  -- https://www.google.com/maps/place/54.2571,-5.6059
  (NULL, 'Ardglass Golf Club',                             'ardglass',                 'Ardglass, Down, Northern Ireland',         'Down',      'https://www.ardglassgolfclub.com/',    54.2571,  -5.6059, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/52.4947,-9.6747
  (NULL, 'Ballybunion Golf Club -- Cashen Course',         'ballybunion-cashen',       'Ballybunion, Kerry, Ireland',              'Kerry',     'https://www.ballybuniongolfclub.com/', 52.4947,  -9.6747, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/52.8532,-6.8940
  (NULL, 'Carlow Golf Club -- Deerpark',                   'carlow-deerpark',          'Carlow, Carlow, Ireland',                  'Carlow',    'https://www.carlowgolfclub.ie/',       52.8532,   -6.894, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.3830,-6.5780
  (NULL, 'Carton House -- Montgomerie',                    'carton-house-montgomerie', 'Maynooth, Kildare, Ireland',               'Kildare',   'https://www.cartonhouse.com/',          53.383,   -6.578, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.3800,-6.5700
  (NULL, 'Carton House -- OMeara',                         'carton-house-omeara',      'Maynooth, Kildare, Ireland',               'Kildare',   'https://www.cartonhouse.com/',           53.38,    -6.57, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.6262,-5.6844
  (NULL, 'Clandeboye Golf Club -- Dufferin',               'clandeboye-dufferin',      'Conlig, Down, Northern Ireland',           'Down',      'https://www.cgc-ni.com/',              54.6262,  -5.6844, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.1084,-6.7022
  (NULL, 'Concra Wood Golf Club',                          'concra-wood',              'Castleblayney, Monaghan, Ireland',         'Monaghan',  'https://www.concrawood.ie/',           54.1084,  -6.7022, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/53.4210,-10.1442
  (NULL, 'Connemara Golf Links -- Championship',           'connemara-championship',   'Ballyconneely, Galway, Ireland',           'Galway',    'https://www.connemaragolflinks.com/',   53.421, -10.1442, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.4723,-6.1255
  (NULL, 'Corballis Links',                                'corballis',                'Donabate, Dublin, Ireland',                'Dublin',    'https://www.corballislinks.com/',      53.4723,  -6.1255, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/51.9014,-8.3544
  (NULL, 'Cork Golf Club',                                 'cork-golf-club',           'Little Island, Cork, Ireland',             'Cork',      'https://www.corkgolfclub.ie/',         51.9014,  -8.3544, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/52.1784,-10.4386
  (NULL, 'Dingle Golf Links -- Ceann Sibeal',              'dingle-ceann-sibeal',      'Ballyferriter, Kerry, Ireland',            'Kerry',     'https://www.dinglelinks.com/',         52.1784, -10.4386, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/52.7811,-8.9047
  (NULL, 'Dromoland Castle Golf Club',                     'dromoland-castle',         'Newmarket-on-Fergus, Clare, Ireland',      'Clare',     'https://www.dromoland.ie/',            52.7811,  -8.9047, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.0932,-6.0785
  (NULL, 'Druids Glen Resort -- Druids Glen',              'druids-glen',              'Newtownmountkennedy, Wicklow, Ireland',    'Wicklow',   'https://www.druidsglenresort.com/',    53.0932,  -6.0785, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/51.8895,-8.2980
  (NULL, 'Fota Island Resort -- Deerpark',                 'fota-island-deerpark',     'Carrigtwohill, Cork, Ireland',             'Cork',      'https://www.fotaisland.ie/',           51.8895,   -8.298, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/53.7245,-6.8595
  (NULL, 'Headfort Golf Club -- New Course',               'headfort-new',             'Kells, Meath, Ireland',                    'Meath',     'https://www.headfortgolfclub.ie/',     53.7245,  -6.8595, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.3635,-6.4131
  (NULL, 'Hermitage Golf Club',                            'hermitage',                'Lucan, Dublin, Ireland',                   'Dublin',    'https://www.hermitagegolf.ie/',        53.3635,  -6.4131, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.3086,-6.6555
  (NULL, 'The K Club -- Palmer North',                     'k-club-palmer-north',      'Straffan, Kildare, Ireland',               'Kildare',   'https://www.kclub.ie/',                53.3086,  -6.6555, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.3120,-6.6600
  (NULL, 'The K Club -- Palmer South',                     'k-club-palmer-south',      'Straffan, Kildare, Ireland',               'Kildare',   'https://www.kclub.ie/',                 53.312,    -6.66, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/52.0638,-9.5445
  (NULL, 'Killarney Golf & Fishing Club -- Killeen',       'killarney-killeen',        'Killarney, Kerry, Ireland',                'Kerry',     'https://www.killarneygolfclub.ie/',    52.0638,  -9.5445, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/52.0460,-9.5560
  (NULL, 'Killarney Golf & Fishing Club -- Mahonys Point', 'killarney-mahonys-point',  'Killarney, Kerry, Ireland',                'Kerry',     'https://www.killarneygolfclub.ie/',     52.046,   -9.556, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.6920,-6.2420
  (NULL, 'Laytown & Bettystown Golf Club',                 'laytown-bettystown',       'Bettystown, Meath, Ireland',               'Meath',     'https://landbgolfclub.ie/',             53.692,   -6.242, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/54.3980,-7.6982
  (NULL, 'Lough Erne Resort -- Faldo Course',              'lough-erne-faldo',         'Enniskillen, Fermanagh, Northern Ireland', 'Fermanagh', 'https://www.lougherneresort.com/',      54.398,  -7.6982, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.5382,-5.9720
  (NULL, 'Malone Golf Club',                               'malone',                   'Dunmurry, Antrim, Northern Ireland',       'Antrim',    'https://www.malonegolfclub.co.uk/',    54.5382,   -5.972, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/52.5259,-7.1887
  (NULL, 'Mount Juliet Estate',                            'mount-juliet',             'Thomastown, Kilkenny, Ireland',            'Kilkenny',  'https://www.mountjuliet.ie/',          52.5259,  -7.1887, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/53.4874,-7.3626
  (NULL, 'Mullingar Golf Club',                            'mullingar',                'Mullingar, Westmeath, Ireland',            'Westmeath', 'https://mullingargolfclub.ie/',        53.4874,  -7.3626, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone')
ON CONFLICT DO NOTHING;

-- ── Ardglass Golf Club (par 71 men / 71 ladies) ──
-- HOLES HIGH: https://ardglassgolfclub.com/course-tour/, https://www.golfpass.com/travel-advisor/courses/18839-ardglass-golf-club, https://18birdies.com/golf-courses/club/7b24be60-86ac-11e4-8c28-020000005b00/ardglass
-- Note: Men's par and SI corroborated (club hole pages, GolfPass, 18Birdies); an outdated par-70 figure and a corrupted aggregator par column were discarded. Ladies SI from the club's own Red-tee pages. Tee ratings single-sourced (golfsherpa), hence LOW.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 10::int, 4::int, 10::int),
  ( 2,      3,      14,      3,      14),
  ( 3,      4,      16,      4,       4),
  ( 4,      4,       6,      4,       6),
  ( 5,      3,      18,      3,      16),
  ( 6,      4,       4,      4,       8),
  ( 7,      3,      12,      3,      18),
  ( 8,      4,       2,      4,       2),
  ( 9,      5,       8,      5,      12),
  (10,      4,      13,      4,      17),
  (11,      5,       3,      5,       3),
  (12,      3,       7,      3,      15),
  (13,      4,       1,      4,       7),
  (14,      4,      11,      4,       1),
  (15,      5,      15,      5,       9),
  (16,      5,       5,      5,       5),
  (17,      3,       9,      3,      13),
  (18,      4,      17,      4,      11)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'ardglass' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Ballybunion Golf Club -- Cashen Course (par 72 men) ──
-- HOLES HIGH: https://www.golfpass.com/travel-advisor/courses/20637-cashen-course-at-ballybunion-golf-club, https://golfsherpa.co.uk/courses/ireland/ballybunion-golf-club-cashen
-- Note: RTJ Sr. second course (1984). Men's card corroborated by GolfPass and golfsherpa. Ladies SI disagrees across sources, so ladies are omitted.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 10::int, NULL::int, NULL::int),
  ( 2,      4,       4,      NULL,      NULL),
  ( 3,      3,      18,      NULL,      NULL),
  ( 4,      4,       8,      NULL,      NULL),
  ( 5,      4,      16,      NULL,      NULL),
  ( 6,      3,      12,      NULL,      NULL),
  ( 7,      4,       6,      NULL,      NULL),
  ( 8,      5,       2,      NULL,      NULL),
  ( 9,      5,      14,      NULL,      NULL),
  (10,      4,      11,      NULL,      NULL),
  (11,      3,      17,      NULL,      NULL),
  (12,      3,      13,      NULL,      NULL),
  (13,      4,       1,      NULL,      NULL),
  (14,      4,       7,      NULL,      NULL),
  (15,      5,       3,      NULL,      NULL),
  (16,      3,      15,      NULL,      NULL),
  (17,      5,       9,      NULL,      NULL),
  (18,      4,       5,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'ballybunion-cashen' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Carlow Golf Club -- Deerpark (par 70 men) ──
-- HOLES HIGH: https://www.golfpass.com/travel-advisor/courses/19183-carlow-golf-club-deerpark-course, https://www.hole19golf.com/courses/carlow-golf-club-deerpark
-- Note: Men's par and SI corroborated by the club's official Golf Ireland WHS card, GolfPass and Hole19; tees from the club's WHS tables. Ladies omitted (no published ladies SI); the rated ladies Red tee (par 75) is left out.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  4::int, NULL::int, NULL::int),
  ( 2,      4,      15,      NULL,      NULL),
  ( 3,      3,      18,      NULL,      NULL),
  ( 4,      4,       9,      NULL,      NULL),
  ( 5,      5,      14,      NULL,      NULL),
  ( 6,      3,      12,      NULL,      NULL),
  ( 7,      4,       1,      NULL,      NULL),
  ( 8,      4,       7,      NULL,      NULL),
  ( 9,      4,       6,      NULL,      NULL),
  (10,      4,      11,      NULL,      NULL),
  (11,      4,       5,      NULL,      NULL),
  (12,      4,       8,      NULL,      NULL),
  (13,      3,      16,      NULL,      NULL),
  (14,      4,       3,      NULL,      NULL),
  (15,      4,      10,      NULL,      NULL),
  (16,      4,       2,      NULL,      NULL),
  (17,      3,      17,      NULL,      NULL),
  (18,      5,      13,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'carlow-deerpark' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Carton House -- Montgomerie (par 72 men) ──
-- HOLES MEDIUM: https://www.hole19golf.com/ireland/carton-house-golf-club-montgomerie, https://www.golfpass.com/travel-advisor/courses/20749-the-montgomerie-course-at-carton-house-golf-club
-- Note: Men's card agreed by Hole19 and GolfPass. Ladies SI single-sourced (GolfPass), so ladies are omitted.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  5::int, NULL::int, NULL::int),
  ( 2,      4,       9,      NULL,      NULL),
  ( 3,      3,       3,      NULL,      NULL),
  ( 4,      5,      13,      NULL,      NULL),
  ( 5,      4,       1,      NULL,      NULL),
  ( 6,      4,      11,      NULL,      NULL),
  ( 7,      3,       7,      NULL,      NULL),
  ( 8,      5,      17,      NULL,      NULL),
  ( 9,      4,      15,      NULL,      NULL),
  (10,      4,       6,      NULL,      NULL),
  (11,      4,       2,      NULL,      NULL),
  (12,      3,      10,      NULL,      NULL),
  (13,      4,      14,      NULL,      NULL),
  (14,      4,       8,      NULL,      NULL),
  (15,      5,      16,      NULL,      NULL),
  (16,      4,       4,      NULL,      NULL),
  (17,      3,      12,      NULL,      NULL),
  (18,      5,      18,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'carton-house-montgomerie' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Carton House -- OMeara (par 73 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20750-the-omeara-course-at-carton-house-golf-club, https://golftraxx.com/scorecard?course_name=Carton+House,+O+Meara+Course&zipcode=IRELAND&static=true
-- Note: O'Meara parkland course. Men's card agreed by GolfPass and golftraxx (par 73). Ladies omitted (no corroborated card); the Red tee (par 74) is dropped.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 14::int, NULL::int, NULL::int),
  ( 2,      3,       6,      NULL,      NULL),
  ( 3,      4,       8,      NULL,      NULL),
  ( 4,      5,      12,      NULL,      NULL),
  ( 5,      4,       4,      NULL,      NULL),
  ( 6,      5,      10,      NULL,      NULL),
  ( 7,      3,      18,      NULL,      NULL),
  ( 8,      4,       2,      NULL,      NULL),
  ( 9,      4,      16,      NULL,      NULL),
  (10,      4,      11,      NULL,      NULL),
  (11,      4,       1,      NULL,      NULL),
  (12,      4,      13,      NULL,      NULL),
  (13,      4,      15,      NULL,      NULL),
  (14,      3,       7,      NULL,      NULL),
  (15,      5,       5,      NULL,      NULL),
  (16,      3,       9,      NULL,      NULL),
  (17,      5,      17,      NULL,      NULL),
  (18,      4,       3,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'carton-house-omeara' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Clandeboye Golf Club -- Dufferin (par 71 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/18916-clandeboye-golf-club-dufferin, https://offcourse.co/courses/scorecard/clandeboye-golf-club/
-- Note: Dufferin championship course. Men's card agreed by GolfPass and offcourse; the club's own card was robots-blocked. Ladies omitted (uncorroborated). Official domain cgc-ni.com.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  9::int, NULL::int, NULL::int),
  ( 2,      3,       5,      NULL,      NULL),
  ( 3,      4,      13,      NULL,      NULL),
  ( 4,      4,       1,      NULL,      NULL),
  ( 5,      3,      15,      NULL,      NULL),
  ( 6,      5,      17,      NULL,      NULL),
  ( 7,      4,       7,      NULL,      NULL),
  ( 8,      4,       3,      NULL,      NULL),
  ( 9,      4,      11,      NULL,      NULL),
  (10,      4,       4,      NULL,      NULL),
  (11,      3,      14,      NULL,      NULL),
  (12,      5,       6,      NULL,      NULL),
  (13,      4,      12,      NULL,      NULL),
  (14,      3,       8,      NULL,      NULL),
  (15,      5,      16,      NULL,      NULL),
  (16,      4,       2,      NULL,      NULL),
  (17,      4,      18,      NULL,      NULL),
  (18,      4,      10,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'clandeboye-dufferin' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Concra Wood Golf Club (par 72 men / 74 ladies) ──
-- HOLES MEDIUM: https://www.concrawood.ie/site/wp-content/uploads/2026/05/New-Scorecard-JPG-1.jpg, https://www.concrawood.ie/score-card/
-- Note: Men's and ladies cards from the club's official scorecard and 2026 WHS handicap tables; single authoritative source (aggregators lacked hole data). Ladies play the 10th and 17th as par 5s (ladies par 74).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 13::int, 5::int, 14::int),
  ( 2,      4,       3,      4,       6),
  ( 3,      4,      17,      4,      16),
  ( 4,      5,       5,      5,       4),
  ( 5,      4,       1,      4,       2),
  ( 6,      3,      15,      3,      18),
  ( 7,      4,      11,      4,      10),
  ( 8,      4,       7,      4,       8),
  ( 9,      3,       9,      3,      12),
  (10,      4,       6,      5,      13),
  (11,      4,       4,      4,       1),
  (12,      3,      16,      3,      11),
  (13,      5,      12,      5,       3),
  (14,      3,      18,      3,      17),
  (15,      5,      14,      5,      15),
  (16,      4,       2,      4,       5),
  (17,      4,       8,      5,       9),
  (18,      4,      10,      4,       7)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'concra-wood' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Connemara Golf Links -- Championship (par 72 men) ──
-- HOLES MEDIUM: https://www.connemaragolflinks.com/scorecard.html, https://www.golfpass.com/travel-advisor/courses/20932-connemara-championship-golf-links-a-b-course, https://golfsherpa.co.uk/courses/northern-ireland/connemara-golf-club-a-b
-- Note: Stroke index and tee ratings from the club's current official scorecard; aggregators carry an older card and disagree. The official ladies SI is not independently corroborated, so ladies are omitted.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  5::int, NULL::int, NULL::int),
  ( 2,      4,       7,      NULL,      NULL),
  ( 3,      3,      17,      NULL,      NULL),
  ( 4,      4,      11,      NULL,      NULL),
  ( 5,      4,       9,      NULL,      NULL),
  ( 6,      3,      15,      NULL,      NULL),
  ( 7,      5,      16,      NULL,      NULL),
  ( 8,      4,       1,      NULL,      NULL),
  ( 9,      4,      13,      NULL,      NULL),
  (10,      4,       6,      NULL,      NULL),
  (11,      3,      18,      NULL,      NULL),
  (12,      4,       2,      NULL,      NULL),
  (13,      3,      10,      NULL,      NULL),
  (14,      5,      14,      NULL,      NULL),
  (15,      4,       3,      NULL,      NULL),
  (16,      4,       4,      NULL,      NULL),
  (17,      5,      12,      NULL,      NULL),
  (18,      5,       8,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'connemara-championship' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Corballis Links (par 66 men) ──
-- HOLES MEDIUM: https://www.thesocialgolfer.com/golf-courses/ireland/co-dublin/corballis-links-golf-club/scorecard/corballis-links-golf-club-white-tee-scorecard, https://offcourse.co/courses/scorecard/corballis-golf-links
-- Note: Par-66 public links. Men's par and SI agreed by three aggregators; the club site confirms par 66. Tees single-sourced (golfsherpa).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 3::int, 13::int, NULL::int, NULL::int),
  ( 2,      4,      17,      NULL,      NULL),
  ( 3,      4,       1,      NULL,      NULL),
  ( 4,      3,      15,      NULL,      NULL),
  ( 5,      4,       7,      NULL,      NULL),
  ( 6,      3,       9,      NULL,      NULL),
  ( 7,      4,      11,      NULL,      NULL),
  ( 8,      4,       3,      NULL,      NULL),
  ( 9,      3,       5,      NULL,      NULL),
  (10,      3,      18,      NULL,      NULL),
  (11,      4,      14,      NULL,      NULL),
  (12,      5,      16,      NULL,      NULL),
  (13,      3,       8,      NULL,      NULL),
  (14,      4,       4,      NULL,      NULL),
  (15,      4,      12,      NULL,      NULL),
  (16,      4,       2,      NULL,      NULL),
  (17,      3,      10,      NULL,      NULL),
  (18,      4,       6,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'corballis' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Cork Golf Club (par 72 men) ──
-- HOLES MEDIUM: https://offcourse.co/courses/scorecard/cork-golf-club, https://www.golfpass.com/travel-advisor/courses/19571-cork-golf-club
-- Note: Little Island (MacKenzie). Men's card agreed by offcourse and GolfPass. Only the Green tee had a corroborated rating and slope. Ladies omitted (uncorroborated).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  9::int, NULL::int, NULL::int),
  ( 2,      5,      15,      NULL,      NULL),
  ( 3,      4,      17,      NULL,      NULL),
  ( 4,      4,       1,      NULL,      NULL),
  ( 5,      5,       5,      NULL,      NULL),
  ( 6,      4,      13,      NULL,      NULL),
  ( 7,      3,       7,      NULL,      NULL),
  ( 8,      4,       3,      NULL,      NULL),
  ( 9,      3,      11,      NULL,      NULL),
  (10,      4,       2,      NULL,      NULL),
  (11,      5,      18,      NULL,      NULL),
  (12,      4,      12,      NULL,      NULL),
  (13,      3,      14,      NULL,      NULL),
  (14,      4,      10,      NULL,      NULL),
  (15,      4,       6,      NULL,      NULL),
  (16,      4,      16,      NULL,      NULL),
  (17,      4,       8,      NULL,      NULL),
  (18,      4,       4,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'cork-golf-club' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Dingle Golf Links -- Ceann Sibeal (par 72 men) ──
-- HOLES HIGH: https://www.dinglelinks.com/wp-content/uploads/2026/06/75287-Dingle-6-Pg-pages.pdf, https://www.golfpass.com/travel-advisor/courses/20647-ceann-sibeal-dingle-golf-club, https://golftraxx.com/scorecard?course_name=Dingle+Golf+Club+(Ceann+Sibeal)&zipcode=KERRY&static=true
-- Note: Men's card triple-corroborated (official scorecard PDF, GolfPass, golftraxx); par 72 despite the site prose loosely saying par 70. Ladies SI conflicts across sources, so ladies are omitted.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  9::int, NULL::int, NULL::int),
  ( 2,      3,      11,      NULL,      NULL),
  ( 3,      4,       3,      NULL,      NULL),
  ( 4,      4,      15,      NULL,      NULL),
  ( 5,      3,      13,      NULL,      NULL),
  ( 6,      5,       7,      NULL,      NULL),
  ( 7,      4,       5,      NULL,      NULL),
  ( 8,      4,      17,      NULL,      NULL),
  ( 9,      4,       1,      NULL,      NULL),
  (10,      3,       8,      NULL,      NULL),
  (11,      5,      16,      NULL,      NULL),
  (12,      3,      10,      NULL,      NULL),
  (13,      5,       2,      NULL,      NULL),
  (14,      4,      18,      NULL,      NULL),
  (15,      4,       4,      NULL,      NULL),
  (16,      4,      12,      NULL,      NULL),
  (17,      4,       6,      NULL,      NULL),
  (18,      5,      14,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'dingle-ceann-sibeal' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Dromoland Castle Golf Club (par 72 men) ──
-- HOLES MEDIUM: http://www.dromoland.ie/wp-content/uploads/pdf/Dromoland-Golf-Course-Map-Scorecard.pdf, https://www.claregolfcourseguide.com/dromoland.html
-- Note: Men's card agreed by the official scorecard PDF and the Clare Golf Course Guide. Ladies SI single-sourced, so ladies are omitted. Black/Red tees dropped (no slope on the card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  8::int, NULL::int, NULL::int),
  ( 2,      4,       4,      NULL,      NULL),
  ( 3,      3,      10,      NULL,      NULL),
  ( 4,      5,      18,      NULL,      NULL),
  ( 5,      4,      12,      NULL,      NULL),
  ( 6,      5,       2,      NULL,      NULL),
  ( 7,      3,      14,      NULL,      NULL),
  ( 8,      4,       6,      NULL,      NULL),
  ( 9,      4,      16,      NULL,      NULL),
  (10,      4,      13,      NULL,      NULL),
  (11,      5,       5,      NULL,      NULL),
  (12,      4,      11,      NULL,      NULL),
  (13,      3,      15,      NULL,      NULL),
  (14,      4,       3,      NULL,      NULL),
  (15,      4,      17,      NULL,      NULL),
  (16,      4,       1,      NULL,      NULL),
  (17,      3,       9,      NULL,      NULL),
  (18,      5,       7,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'dromoland-castle' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Druids Glen Resort -- Druids Glen (par 72 men / 73 ladies) ──
-- HOLES HIGH: https://www.druidsglenresort.com/wp-content/uploads/2026/07/Druids-Glen-Scorecard-2024-New.pdf, https://www.golfpass.com/travel-advisor/courses/20625-druids-glen-golf-club-at-druids-glen-golf-resort
-- Note: Current course is par 72 (18th a par 5); older aggregators show a par-71 layout and were discarded. Men's and ladies cards from the official 2024 scorecard, corroborated by GolfPass. Ladies play the 6th as a par 5.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  8::int, 4::int, 10::int),
  ( 2,      3,      16,      3,      18),
  ( 3,      4,      12,      4,       6),
  ( 4,      4,       4,      4,       4),
  ( 5,      5,       6,      5,      12),
  ( 6,      4,       2,      5,      14),
  ( 7,      4,      14,      4,       8),
  ( 8,      3,      18,      3,      16),
  ( 9,      4,      10,      4,       2),
  (10,      4,       7,      4,       5),
  (11,      5,      13,      5,      13),
  (12,      3,      17,      3,      17),
  (13,      4,       1,      4,       1),
  (14,      4,      15,      4,      11),
  (15,      4,       5,      4,       3),
  (16,      5,       9,      5,       9),
  (17,      3,       3,      3,      15),
  (18,      5,      11,      5,       7)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'druids-glen' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Fota Island Resort -- Deerpark (par 71 men / 72 ladies) ──
-- HOLES MEDIUM: https://www.fotaisland.ie/contentfiles/D03_30292%20Deerpark%20Score%204.pdf, https://www.hole19golf.com/ireland/fota-island-resort-deerpark
-- Note: Deerpark championship 18. Men's and ladies cards from the club's official scorecard PDF, men's matched by Hole19 and the ladies total by GolfPass. Ladies play the 8th as a par 5.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  7::int, 4::int,  4::int),
  ( 2,      4,       3,      4,       6),
  ( 3,      3,       9,      3,      16),
  ( 4,      5,      15,      5,       8),
  ( 5,      5,      17,      5,      14),
  ( 6,      4,      13,      4,      12),
  ( 7,      3,      11,      3,      18),
  ( 8,      4,       1,      5,      10),
  ( 9,      4,       5,      4,       2),
  (10,      5,      16,      5,       9),
  (11,      3,      14,      3,      17),
  (12,      4,       4,      4,       3),
  (13,      3,      12,      3,      13),
  (14,      4,       2,      4,       1),
  (15,      4,       6,      4,       7),
  (16,      4,       8,      4,       5),
  (17,      3,      10,      3,      15),
  (18,      5,      18,      5,      11)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'fota-island-deerpark' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Headfort Golf Club -- New Course (par 72 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20825-new-course-at-headfort-golf-club, https://www.gogolfing.ie/golf-course.php?id_club=318
-- Note: New (championship) course. Men's card agreed by GolfPass and gogolfing. Ladies omitted (no corroborated ladies card); tees from coursehandicap.com.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  6::int, NULL::int, NULL::int),
  ( 2,      5,      18,      NULL,      NULL),
  ( 3,      4,      10,      NULL,      NULL),
  ( 4,      3,      14,      NULL,      NULL),
  ( 5,      4,       2,      NULL,      NULL),
  ( 6,      5,       8,      NULL,      NULL),
  ( 7,      3,      16,      NULL,      NULL),
  ( 8,      4,       4,      NULL,      NULL),
  ( 9,      4,      12,      NULL,      NULL),
  (10,      4,       9,      NULL,      NULL),
  (11,      3,      11,      NULL,      NULL),
  (12,      4,       5,      NULL,      NULL),
  (13,      4,       1,      NULL,      NULL),
  (14,      5,      15,      NULL,      NULL),
  (15,      4,       3,      NULL,      NULL),
  (16,      5,      17,      NULL,      NULL),
  (17,      3,      13,      NULL,      NULL),
  (18,      4,       7,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'headfort-new' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Hermitage Golf Club (par 71 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20237-hermitage-golf-club, https://offcourse.co/courses/scorecard/hermitage-golf-club
-- Note: Men's par agreed by four aggregators; SI by GolfPass, offcourse and golftraxx (18Birdies rejected). Ladies omitted (single-sourced).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 16::int, NULL::int, NULL::int),
  ( 2,      4,       2,      NULL,      NULL),
  ( 3,      4,       6,      NULL,      NULL),
  ( 4,      3,      14,      NULL,      NULL),
  ( 5,      4,      12,      NULL,      NULL),
  ( 6,      4,      18,      NULL,      NULL),
  ( 7,      3,      10,      NULL,      NULL),
  ( 8,      4,       4,      NULL,      NULL),
  ( 9,      5,       8,      NULL,      NULL),
  (10,      3,      15,      NULL,      NULL),
  (11,      5,       1,      NULL,      NULL),
  (12,      4,       3,      NULL,      NULL),
  (13,      3,      17,      NULL,      NULL),
  (14,      4,      13,      NULL,      NULL),
  (15,      5,      11,      NULL,      NULL),
  (16,      4,       7,      NULL,      NULL),
  (17,      4,       9,      NULL,      NULL),
  (18,      4,       5,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'hermitage' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── The K Club -- Palmer North (par 72 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20764-the-k-club-the-palmer-north-course, https://www.hole19golf.com/courses/the-k-club-palmer-north
-- Note: 2006 Ryder Cup course. Current routing agreed by GolfPass and Hole19; an older nines-swapped Ryder Cup card was discarded. Ladies omitted (no corroborated ladies card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int,  6::int, NULL::int, NULL::int),
  ( 2,      4,      12,      NULL,      NULL),
  ( 3,      3,      18,      NULL,      NULL),
  ( 4,      4,       8,      NULL,      NULL),
  ( 5,      3,      16,      NULL,      NULL),
  ( 6,      4,      10,      NULL,      NULL),
  ( 7,      5,       2,      NULL,      NULL),
  ( 8,      4,      14,      NULL,      NULL),
  ( 9,      4,       4,      NULL,      NULL),
  (10,      4,       9,      NULL,      NULL),
  (11,      4,       3,      NULL,      NULL),
  (12,      3,      17,      NULL,      NULL),
  (13,      5,      11,      NULL,      NULL),
  (14,      4,       7,      NULL,      NULL),
  (15,      4,       5,      NULL,      NULL),
  (16,      4,       1,      NULL,      NULL),
  (17,      3,      15,      NULL,      NULL),
  (18,      5,      13,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'k-club-palmer-north' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── The K Club -- Palmer South (par 72 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20765-the-k-club-the-palmer-south-course, https://ecaddy.co.za/gcl/courses/kclubpalmersouth/
-- Note: Palmer South (Smurfit) course. Men's card agreed by GolfPass and eCaddy (the K Club's linked course-guide). Ladies omitted (single-sourced).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  6::int, NULL::int, NULL::int),
  ( 2,      3,      16,      NULL,      NULL),
  ( 3,      5,       8,      NULL,      NULL),
  ( 4,      4,      10,      NULL,      NULL),
  ( 5,      4,      14,      NULL,      NULL),
  ( 6,      4,       4,      NULL,      NULL),
  ( 7,      5,      12,      NULL,      NULL),
  ( 8,      3,      18,      NULL,      NULL),
  ( 9,      4,       2,      NULL,      NULL),
  (10,      5,      11,      NULL,      NULL),
  (11,      4,      17,      NULL,      NULL),
  (12,      3,      15,      NULL,      NULL),
  (13,      4,       3,      NULL,      NULL),
  (14,      4,       7,      NULL,      NULL),
  (15,      4,      13,      NULL,      NULL),
  (16,      4,       1,      NULL,      NULL),
  (17,      3,       9,      NULL,      NULL),
  (18,      5,       5,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'k-club-palmer-south' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Killarney Golf & Fishing Club -- Killeen (par 72 men) ──
-- HOLES MEDIUM: https://www.killarneygolfclub.ie/golf-courses/killeen/, https://www.golfpass.com/travel-advisor/courses/20692-killarney-golf-and-fishing-club-killeen
-- Note: Men's card from the club's current card; par corroborated by GolfPass and golftraxx, SI by GolfPass (16/18). Ladies omitted (no corroborated ladies card). Site killarney-golf.com now redirects elsewhere; killarneygolfclub.ie is current.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  8::int, NULL::int, NULL::int),
  ( 2,      4,      16,      NULL,      NULL),
  ( 3,      3,      10,      NULL,      NULL),
  ( 4,      4,      14,      NULL,      NULL),
  ( 5,      4,       4,      NULL,      NULL),
  ( 6,      3,      12,      NULL,      NULL),
  ( 7,      5,      18,      NULL,      NULL),
  ( 8,      4,       2,      NULL,      NULL),
  ( 9,      4,       6,      NULL,      NULL),
  (10,      3,      11,      NULL,      NULL),
  (11,      5,      17,      NULL,      NULL),
  (12,      4,       5,      NULL,      NULL),
  (13,      4,       1,      NULL,      NULL),
  (14,      4,      13,      NULL,      NULL),
  (15,      4,       9,      NULL,      NULL),
  (16,      5,      15,      NULL,      NULL),
  (17,      4,       7,      NULL,      NULL),
  (18,      4,       3,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'killarney-killeen' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Killarney Golf & Fishing Club -- Mahonys Point (par 72 men) ──
-- HOLES HIGH: https://killarneygolfclub.ie/golf-courses/mahonys-point, https://www.golfpass.com/travel-advisor/courses/20690-killarney-golf-and-fishing-club-mahonys-point
-- Note: Second course at Killarney. Men's card agreed by the club card and GolfPass. Ladies omitted (no corroborated ladies card); the rated par-74 Red tee is dropped.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 12::int, NULL::int, NULL::int),
  ( 2,      4,       4,      NULL,      NULL),
  ( 3,      4,       2,      NULL,      NULL),
  ( 4,      3,      14,      NULL,      NULL),
  ( 5,      5,      16,      NULL,      NULL),
  ( 6,      4,       8,      NULL,      NULL),
  ( 7,      3,      10,      NULL,      NULL),
  ( 8,      5,       6,      NULL,      NULL),
  ( 9,      4,      18,      NULL,      NULL),
  (10,      4,       9,      NULL,      NULL),
  (11,      4,       1,      NULL,      NULL),
  (12,      3,      11,      NULL,      NULL),
  (13,      5,      13,      NULL,      NULL),
  (14,      4,       5,      NULL,      NULL),
  (15,      4,      17,      NULL,      NULL),
  (16,      5,      15,      NULL,      NULL),
  (17,      4,       3,      NULL,      NULL),
  (18,      3,       7,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'killarney-mahonys-point' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Laytown & Bettystown Golf Club (par 71 men / 73 ladies) ──
-- HOLES HIGH: https://landbgolfclub.ie/assets/uploads/documents/LaytownAndBettystownScoreCardDec2021.pdf, https://landbgolfclub.ie/course/course-handicap-tables/
-- Note: Men's and ladies cards from the club's official scorecard and 2024 WHS handicap tables. Ladies play the 11th and 15th as par 5s (ladies par 73).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 12::int, 4::int,  9::int),
  ( 2,      4,      14,      4,      17),
  ( 3,      4,       4,      4,       3),
  ( 4,      5,      16,      5,       7),
  ( 5,      4,       6,      4,       1),
  ( 6,      3,      10,      3,      11),
  ( 7,      4,       2,      4,       6),
  ( 8,      3,       8,      3,      10),
  ( 9,      4,      18,      4,      15),
  (10,      4,      11,      4,       2),
  (11,      4,       5,      5,      16),
  (12,      3,      13,      3,      13),
  (13,      4,       3,      4,       4),
  (14,      4,       9,      4,       5),
  (15,      4,       1,      5,      14),
  (16,      4,       7,      4,       8),
  (17,      4,      17,      4,      12),
  (18,      5,      15,      5,      18)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'laytown-bettystown' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Lough Erne Resort -- Faldo Course (par 72 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/28849-lough-erne-resort-faldo-championship-course, https://golfsherpa.co.uk/courses/northern-ireland/lough-erne-resort
-- Note: Faldo course. Men's card agreed by GolfPass and golfsherpa, individual pars confirmed by the club site. Ladies omitted (no corroborated ladies card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  5::int, NULL::int, NULL::int),
  ( 2,      4,      11,      NULL,      NULL),
  ( 3,      3,      17,      NULL,      NULL),
  ( 4,      5,      15,      NULL,      NULL),
  ( 5,      3,       9,      NULL,      NULL),
  ( 6,      5,       7,      NULL,      NULL),
  ( 7,      4,      13,      NULL,      NULL),
  ( 8,      4,       1,      NULL,      NULL),
  ( 9,      5,       3,      NULL,      NULL),
  (10,      4,      16,      NULL,      NULL),
  (11,      4,      12,      NULL,      NULL),
  (12,      4,       4,      NULL,      NULL),
  (13,      3,       8,      NULL,      NULL),
  (14,      5,       2,      NULL,      NULL),
  (15,      3,      18,      NULL,      NULL),
  (16,      5,      14,      NULL,      NULL),
  (17,      4,       6,      NULL,      NULL),
  (18,      3,      10,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'lough-erne-faldo' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Malone Golf Club (par 71 men / 73 ladies) ──
-- HOLES MEDIUM: https://malonegolfclub.co.uk/wp-content/uploads/2022/07/MALONE-GC-SCORE-CARD-V3C.pdf, https://www.golfshake.com/course/view/15425/Malone_Golf_Club.html
-- Note: Championship course (Drumbridge/Ballydrain), from the club's official scorecard; aggregators disagree on routing and were discarded. Ladies play the 7th and 14th as par 5s.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  5::int, 4::int,  5::int),
  ( 2,      5,      11,      5,      11),
  ( 3,      5,       9,      5,       9),
  ( 4,      3,      17,      3,      15),
  ( 5,      4,       3,      4,       1),
  ( 6,      3,      15,      3,      17),
  ( 7,      4,       1,      5,      13),
  ( 8,      4,      13,      4,       3),
  ( 9,      4,       7,      4,       7),
  (10,      4,      10,      4,       4),
  (11,      4,       8,      4,       6),
  (12,      3,      12,      3,      18),
  (13,      4,       4,      4,       2),
  (14,      4,       2,      5,      14),
  (15,      3,      16,      3,      12),
  (16,      4,      18,      4,      10),
  (17,      5,      14,      5,      16),
  (18,      4,       6,      4,       8)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'malone' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Mount Juliet Estate (par 72 men / 72 ladies) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20810-mount-juliet-golf-club, https://18birdies.com/golf-courses/club/7b9ef770-86ac-11e4-8c28-020000005b00/mount-juliet-golf-course, https://golftraxx.com/scorecard?course_name=Mount+Juliet+Estate+Golf+Course&zipcode=KILKENNY&static=true
-- Note: Men's card corroborated by GolfPass, 18Birdies and golftraxx; ladies card by GolfPass and golftraxx. No official scorecard online (Ireland uses CONGU), hence MEDIUM.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 16::int, 4::int, 14::int),
  ( 2,      4,       4,      4,       2),
  ( 3,      3,      14,      3,      18),
  ( 4,      4,       2,      4,      10),
  ( 5,      5,      18,      5,      12),
  ( 6,      3,       6,      3,      16),
  ( 7,      4,      12,      4,       8),
  ( 8,      5,      10,      5,       6),
  ( 9,      4,       8,      4,       4),
  (10,      5,       7,      5,       3),
  (11,      3,      17,      3,      17),
  (12,      4,       9,      4,       7),
  (13,      4,       1,      4,       1),
  (14,      3,      11,      3,      11),
  (15,      4,      15,      4,      13),
  (16,      4,       5,      4,       9),
  (17,      5,      13,      5,       5),
  (18,      4,       3,      4,      15)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'mount-juliet' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Mullingar Golf Club (par 72 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/courses/25847-mullingar-golf-club/scorecards, https://www.hole19golf.com/courses/mullingar-golf-club, https://mullingargolfclub.ie/course-guide/
-- Note: James Braid course. Par corroborated by the club guide, GolfPass and Hole19; SI from GolfPass (Hole19 agrees 16/18). Ladies omitted (no corroborated ladies card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 15::int, NULL::int, NULL::int),
  ( 2,      3,       5,      NULL,      NULL),
  ( 3,      4,       9,      NULL,      NULL),
  ( 4,      5,       3,      NULL,      NULL),
  ( 5,      3,      11,      NULL,      NULL),
  ( 6,      4,      13,      NULL,      NULL),
  ( 7,      4,       1,      NULL,      NULL),
  ( 8,      4,       7,      NULL,      NULL),
  ( 9,      4,      17,      NULL,      NULL),
  (10,      4,       2,      NULL,      NULL),
  (11,      4,       6,      NULL,      NULL),
  (12,      3,      14,      NULL,      NULL),
  (13,      4,       8,      NULL,      NULL),
  (14,      5,      18,      NULL,      NULL),
  (15,      3,      12,      NULL,      NULL),
  (16,      5,      10,      NULL,      NULL),
  (17,      4,       4,      NULL,      NULL),
  (18,      5,      16,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'mullingar' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO tees (course_id, name, gender, par, course_rating, slope)
SELECT c.id, spec.tee_name, spec.gender, spec.par::integer,
       spec.course_rating::numeric, spec.slope::integer
FROM (VALUES
  -- ── Ardglass Golf Club ──
  -- TEES LOW: https://golfsherpa.co.uk/courses/northern-ireland/ardglass-golf-club
  ('ardglass',                 'White',        'M', 71, 70.6, 118),
  ('ardglass',                 'Green',        'M', 71, 68.6, 114),
  ('ardglass',                 'Red',          'F', 71, 71.1, 118),

  -- ── Ballybunion Golf Club -- Cashen Course ──
  -- TEES HIGH: https://www.golfpass.com/travel-advisor/courses/20637-cashen-course-at-ballybunion-golf-club, https://golfsherpa.co.uk/courses/ireland/ballybunion-golf-club-cashen
  ('ballybunion-cashen',       'Blue',         'M', 72, 72.3, 130),
  ('ballybunion-cashen',       'White',        'M', 72, 70.8, 127),
  ('ballybunion-cashen',       'Green',        'M', 72, 69.1, 121),
  ('ballybunion-cashen',       'Red',          'F', 72, 72.3, 133),

  -- ── Carlow Golf Club -- Deerpark ──
  -- TEES HIGH: https://www.carlowgolfclub.ie/uploads/1/5/4/5/154571604/whs_deerpark_white.pdf
  ('carlow-deerpark',          'Blue',         'M', 70, 72.4, 127),
  ('carlow-deerpark',          'White',        'M', 70, 71.2, 124),
  ('carlow-deerpark',          'Green',        'M', 70, 65.0, 114),

  -- ── Carton House -- Montgomerie ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20749-the-montgomerie-course-at-carton-house-golf-club
  ('carton-house-montgomerie', 'Blue',         'M', 72, 75.3, 140),
  ('carton-house-montgomerie', 'White',        'M', 72, 73.1, 136),
  ('carton-house-montgomerie', 'Green',        'M', 72, 70.7, 132),

  -- ── Carton House -- OMeara ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20750-the-omeara-course-at-carton-house-golf-club
  ('carton-house-omeara',      'Blue',         'M', 73, 75.1, 134),
  ('carton-house-omeara',      'White',        'M', 73, 73.4, 129),
  ('carton-house-omeara',      'Green',        'M', 73, 71.2, 126),

  -- ── Clandeboye Golf Club -- Dufferin ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/18916-clandeboye-golf-club-dufferin, https://www.golfnow.co.uk/courses/-518-clandeboye-golf-club-dufferin-course-details
  ('clandeboye-dufferin',      'Blue',         'M', 71, 72.1, 121),
  ('clandeboye-dufferin',      'White',        'M', 71, 71.0, 120),
  ('clandeboye-dufferin',      'Green',        'M', 71, 69.7, 119),
  ('clandeboye-dufferin',      'Yellow',       'M', 71, 67.5, 114),

  -- ── Concra Wood Golf Club ──
  -- TEES MEDIUM: https://www.concrawood.ie/site/wp-content/uploads/2026/05/Black-Tees-Course-Handicap-Table-2026-1.pdf, https://www.concrawood.ie/site/wp-content/uploads/2026/05/Ladies-Red-Tees-Course-Handicap-Table-2026-1.pdf
  ('concra-wood',              'Black',        'M', 72, 74.7, 134),
  ('concra-wood',              'Gold',         'M', 72, 73.3, 129),
  ('concra-wood',              'Green',        'M', 72, 72.2, 127),
  ('concra-wood',              'White',        'M', 72, 69.9, 125),
  ('concra-wood',              'Red',          'F', 74, 73.9, 128),

  -- ── Connemara Golf Links -- Championship ──
  -- TEES MEDIUM: https://www.connemaragolflinks.com/scorecard.html
  ('connemara-championship',   'Blue',         'M', 72, 75.1, 130),
  ('connemara-championship',   'White',        'M', 72, 73.6, 131),
  ('connemara-championship',   'Yellow',       'M', 72, 71.8, 124),
  ('connemara-championship',   'Green',        'M', 72, 67.3, 115),

  -- ── Corballis Links ──
  -- TEES MEDIUM: https://golfsherpa.co.uk/courses/northern-ireland/corballis-links-golf-club
  ('corballis',                'Blue',         'M', 66, 65.7, 114),
  ('corballis',                'Red',          'M', 66, 63.3, 104),
  ('corballis',                'Red',          'F', 66, 66.0, 109),

  -- ── Cork Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/19571-cork-golf-club, https://drills.golf/course/cork-golf-club-little-island
  ('cork-golf-club',           'Green',        'M', 72, 70.4, 132),

  -- ── Dingle Golf Links -- Ceann Sibeal ──
  -- TEES HIGH: https://www.dinglelinks.com/wp-content/uploads/2026/06/handicap-table.pdf, https://www.dinglelinks.com/wp-content/uploads/2026/06/75287-Dingle-6-Pg-pages.pdf
  ('dingle-ceann-sibeal',      'Blue',         'M', 72, 72.8, 137),
  ('dingle-ceann-sibeal',      'White',        'M', 72, 71.1, 134),
  ('dingle-ceann-sibeal',      'Yellow',       'M', 72, 69.6, 131),

  -- ── Dromoland Castle Golf Club ──
  -- TEES MEDIUM: http://www.dromoland.ie/wp-content/uploads/pdf/Dromoland-Golf-Course-Map-Scorecard.pdf
  ('dromoland-castle',         'Blue',         'M', 72, 73.0, 129),
  ('dromoland-castle',         'White',        'M', 72, 70.5, 125),
  ('dromoland-castle',         'Yellow',       'M', 72, 69.4, 124),

  -- ── Druids Glen Resort -- Druids Glen ──
  -- TEES MEDIUM: https://www.druidsglenresort.com/wp-content/uploads/2026/07/Druids-Glen-Scorecard-2024-New.pdf, https://www.golfpass.com/travel-advisor/courses/20625-druids-glen-golf-club-at-druids-glen-golf-resort, https://golfsherpa.co.uk/courses/northern-ireland/druids-glen-golf-resort-druids-glen
  ('druids-glen',              'Gold',         'M', 72, 75.4, 139),
  ('druids-glen',              'White',        'M', 72, 73.0, 134),
  ('druids-glen',              'Green',        'M', 72, 70.4, 127),
  ('druids-glen',              'Red',          'F', 73, 72.2, 125),

  -- ── Fota Island Resort -- Deerpark ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/19557-fota-island-golf-club-deerpark-course
  ('fota-island-deerpark',     'Championship', 'M', 71, 73.5, 131),
  ('fota-island-deerpark',     'Medal',        'M', 71, 71.3, 128),
  ('fota-island-deerpark',     'Society',      'M', 71, 69.7, 121),
  ('fota-island-deerpark',     'Ladies',       'F', 72, 71.7, 122),

  -- ── Headfort Golf Club -- New Course ──
  -- TEES MEDIUM: https://coursehandicap.com/headfort-golf-club-new-course/
  ('headfort-new',             'Blue',         'M', 72, 75.2, 137),
  ('headfort-new',             'White',        'M', 72, 73.5, 132),
  ('headfort-new',             'Yellow',       'M', 72, 72.0, 131),
  ('headfort-new',             'Red',          'F', 72, 72.0, 125),

  -- ── Hermitage Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20237-hermitage-golf-club
  ('hermitage',                'Blue',         'M', 71, 72.4, 127),
  ('hermitage',                'White',        'M', 71, 71.4, 124),
  ('hermitage',                'Green',        'M', 71, 69.0, 117),

  -- ── The K Club -- Palmer North ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20764-the-k-club-the-palmer-north-course
  ('k-club-palmer-north',      'Blue',         'M', 72, 76.1, 138),
  ('k-club-palmer-north',      'White',        'M', 72, 73.7, 133),
  ('k-club-palmer-north',      'Green',        'M', 72, 71.5, 128),

  -- ── The K Club -- Palmer South ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20765-the-k-club-the-palmer-south-course
  ('k-club-palmer-south',      'Blue',         'M', 72, 75.4, 137),
  ('k-club-palmer-south',      'White',        'M', 72, 73.3, 134),
  ('k-club-palmer-south',      'Green',        'M', 72, 71.2, 128),
  ('k-club-palmer-south',      'Red',          'F', 72, 72.3, 138),

  -- ── Killarney Golf & Fishing Club -- Killeen ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20692-killarney-golf-and-fishing-club-killeen
  ('killarney-killeen',        'Blue',         'M', 72, 76.6, 136),
  ('killarney-killeen',        'White',        'M', 72, 74.1, 134),
  ('killarney-killeen',        'Green',        'M', 72, 71.3, 128),

  -- ── Killarney Golf & Fishing Club -- Mahonys Point ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20690-killarney-golf-and-fishing-club-mahonys-point
  ('killarney-mahonys-point',  'Blue',         'M', 72, 72.0, 122),
  ('killarney-mahonys-point',  'White',        'M', 72, 70.2, 120),
  ('killarney-mahonys-point',  'Green',        'M', 72, 68.4, 116),

  -- ── Laytown & Bettystown Golf Club ──
  -- TEES HIGH: https://landbgolfclub.ie/course/course-handicap-tables/
  ('laytown-bettystown',       'White',        'M', 71, 72.0, 126),
  ('laytown-bettystown',       'Green',        'M', 71, 71.2, 125),
  ('laytown-bettystown',       'Yellow',       'M', 71, 68.1, 119),
  ('laytown-bettystown',       'Red',          'F', 73, 73.0, 129),

  -- ── Lough Erne Resort -- Faldo Course ──
  -- TEES MEDIUM: https://golfsherpa.co.uk/courses/northern-ireland/lough-erne-resort
  ('lough-erne-faldo',         'Black',        'M', 72, 74.6, 137),
  ('lough-erne-faldo',         'Blue',         'M', 72, 72.4, 134),
  ('lough-erne-faldo',         'White',        'M', 72, 70.1, 124),
  ('lough-erne-faldo',         'Yellow',       'M', 72, 67.5, 108),
  ('lough-erne-faldo',         'Red',          'M', 72, 64.2, 104),
  ('lough-erne-faldo',         'Yellow',       'F', 72, 72.7, 128),
  ('lough-erne-faldo',         'Red',          'F', 72, 68.8, 115),

  -- ── Malone Golf Club ──
  -- TEES MEDIUM: https://malonegolfclub.co.uk/wp-content/uploads/2022/07/MALONE-GC-SCORE-CARD-V3C.pdf
  ('malone',                   'Blue',         'M', 71, 72.2, 128),
  ('malone',                   'White',        'M', 71, 71.0, 124),
  ('malone',                   'Green',        'M', 71, 69.2, 118),
  ('malone',                   'Green',        'F', 73, 75.5, 132),
  ('malone',                   'Red',          'F', 73, 72.5, 120),

  -- ── Mount Juliet Estate ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/20810-mount-juliet-golf-club, https://18birdies.com/golf-courses/club/7b9ef770-86ac-11e4-8c28-020000005b00/mount-juliet-golf-course
  ('mount-juliet',             'Blue',         'M', 72, 76.1, 143),
  ('mount-juliet',             'White',        'M', 72, 74.6, 140),
  ('mount-juliet',             'Green',        'M', 72, 72.4, 134),
  ('mount-juliet',             'Red',          'F', 72, 72.6, 129),

  -- ── Mullingar Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/courses/25847-mullingar-golf-club/scorecards
  ('mullingar',                'Blue',         'M', 72, 73.3, 133),
  ('mullingar',                'White',        'M', 72, 72.2, 129),
  ('mullingar',                'Yellow',       'M', 72, 70.7, 126)
) AS spec(slug, tee_name, gender, par, course_rating, slope)
JOIN courses c ON c.slug = spec.slug AND c.trip_id IS NULL
ON CONFLICT ON CONSTRAINT uq_tees_course_name_gender DO NOTHING;

COMMIT;

-- ── Did it land? ──────────────────────────────────────────
-- Run this after the COMMIT above. Every course below should come back with
-- its holes and tees. /admin/courses says the same thing with badges.
--
-- select c.slug, c.name, c.county, c.card_verified,
--        (select count(*) from holes h where h.course_id = c.id) as holes,
--        (select count(*) from tees  t where t.course_id = c.id) as tees
-- from courses c
-- where c.trip_id is null
--   and c.slug in ('ardglass', 'ballybunion-cashen', 'carlow-deerpark', 'carton-house-montgomerie', 'carton-house-omeara', 'clandeboye-dufferin', 'concra-wood', 'connemara-championship', 'corballis', 'cork-golf-club', 'dingle-ceann-sibeal', 'dromoland-castle', 'druids-glen', 'fota-island-deerpark', 'headfort-new', 'hermitage', 'k-club-palmer-north', 'k-club-palmer-south', 'killarney-killeen', 'killarney-mahonys-point', 'laytown-bettystown', 'lough-erne-faldo', 'malone', 'mount-juliet', 'mullingar')
-- order by c.name;
