-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/course-tees/*.json — do not hand-edit.
--
-- Tee corrections batch A: 2 courses.
--
-- New ratings for courses already on the platform. Confidence is noted per
-- course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Nothing is deleted. round_handicaps.tee_id is ON DELETE RESTRICT, so a tee
-- somebody has played off cannot be removed — and DO UPDATE is better than
-- that anyway: it keeps tees.id, so every round_handicaps row and every
-- stored scorecard goes on pointing at the same row with corrected numbers.
--
-- **A stored tee this file does not name is left exactly as it is.** Removing
-- a wrong tee is a hand job in the SQL editor, and will be refused outright
-- if anybody has played off it.
--
-- par is NOT taken from the file. It is derived from the stored holes, so a
-- correction a scorecard photo has already made is never reverted. The
-- fallback is diffCard's own: the ladies total for a ladies tee, the men's
-- when that gender has no card, the researched figure only when the course
-- has no card at all.
--
-- Replay-safe: a second run writes the same values again.
-- ============================================================

BEGIN;

INSERT INTO tees (course_id, name, gender, par, course_rating, slope)
SELECT c.id, spec.tee_name, spec.gender, spec.par::integer,
       spec.course_rating::numeric, spec.slope::integer
FROM (VALUES
  -- ── County Sligo Golf Club -- Colt Championship ──
  -- TEES HIGH: https://www.golfireland.ie/
  -- Note: Official WHS ratings from the Golf Ireland app, Aug 2026 — replaces migration 008's estimated White and adds Gold and Green; the Women's Red was not in the source and is left as stored.
  ('county-sligo-colt-championship', 'Black', 'M', 71, 75.9, 135),
  ('county-sligo-colt-championship', 'White', 'M', 71, 72.6, 129),
  ('county-sligo-colt-championship', 'Gold',  'M', 71, 71.4, 128),
  ('county-sligo-colt-championship', 'Green', 'M', 71, 69.8, 124),

  -- ── Enniscrone Golf Club -- The Dunes ──
  -- TEES HIGH: https://www.golfireland.ie/
  -- Note: Official WHS ratings from the Golf Ireland app, Aug 2026 — corrects migration 008's Blue and Black slopes and adds White, Green and Red men's tees plus the Women's Green.
  ('enniscrone-dunes',               'Black', 'M', 73, 74.8, 140),
  ('enniscrone-dunes',               'Blue',  'M', 73, 73.5, 134),
  ('enniscrone-dunes',               'White', 'M', 73, 72.3, 128),
  ('enniscrone-dunes',               'Green', 'M', 73, 70.5, 118),
  ('enniscrone-dunes',               'Red',   'M', 73, 69.3, 110),
  ('enniscrone-dunes',               'Green', 'F', 73, 76.2, 134),
  ('enniscrone-dunes',               'Red',   'F', 73, 74.3, 126)
) AS spec(slug, tee_name, gender, par, course_rating, slope)
JOIN courses c ON c.slug = spec.slug AND c.trip_id IS NULL
ON CONFLICT ON CONSTRAINT uq_tees_course_name_gender DO UPDATE SET
  course_rating = EXCLUDED.course_rating,
  slope         = EXCLUDED.slope,
  par           = COALESCE(
    CASE WHEN tees.gender = 'F' THEN (
      SELECT sum(h.par_ladies) FROM holes h WHERE h.course_id = tees.course_id
    ) END,
    (SELECT sum(h.par) FROM holes h WHERE h.course_id = tees.course_id),
    EXCLUDED.par);

COMMIT;

-- ── Did it land? ──────────────────────────────────────────
-- This runs itself. Every course below should come back with its holes and
-- its tees; /admin/courses says the same thing with badges. Re-pasting the
-- whole file is safe and asks the question again — every write above either
-- skips or rewrites the same values, so a second run leaves the database
-- where the first one left it.
select c.slug, c.name, c.county, c.card_verified,
       (select count(*) from holes h where h.course_id = c.id) as holes,
       (select count(*) from tees  t where t.course_id = c.id) as tees
from courses c
where c.trip_id is null
  and c.slug in ('county-sligo-colt-championship', 'enniscrone-dunes')
order by c.name;
