-- ============================================================
-- GENERATED by scripts/build-course-migration.ts from data/courses/*.json — do not hand-edit.
--
-- Platform courses batch E: 12 courses.
--
-- Confidence is noted per course, in migration 008's words:
--   HIGH   = confirmed from 3+ independent sources
--   MEDIUM = confirmed from 1-2 sources, internally consistent
--   LOW    = single source or conflicting; treat as provisional
--   EST    = estimated; verify against Golf Ireland before use
--
-- Holes are HIGH or MEDIUM only. A wrong stroke index mis-hands shots on
-- every round of this course, forever, and no screen ever says so. Tee
-- ratings may be lower: a wrong slope is a fraction of a shot, and a
-- scorecard photo corrects it.
--
-- card_verified stays false on every row. Where there are holes they make
-- the course playable (`hasCard` is holes.length > 0) and the badge says,
-- honestly, that no photograph has confirmed them — a later photo takes the
-- diff path, because handleCreate refuses a course that already has holes.
-- Where there are none, the course is searchable and carries its weather,
-- scoring is gated, and the first photo takes handleCreate's create path
-- and writes the card.
--
-- Replay-safe: every insert is ON CONFLICT DO NOTHING and nothing here
-- deletes. Migration 008 cleared its tees first; that is no longer safe,
-- because round_handicaps.tee_id is ON DELETE RESTRICT and a tee somebody
-- has played off cannot be removed.
-- ============================================================

BEGIN;

INSERT INTO courses
  (trip_id, name, slug, location, county, website, latitude, longitude,
   geocoded_at, card_verified, ladies_data_verified, ladies_data_note)
VALUES
  -- https://www.google.com/maps/place/55.1292,-7.4578
  (NULL, 'North West Golf Club',                     'north-west',          'Buncrana, Donegal, Ireland',        'Donegal', 'https://www.northwestgolfclub.com/',      55.1292, -7.4578, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/53.4296,-6.1287
  (NULL, 'Portmarnock Resort -- Jameson Golf Links', 'portmarnock-jameson', 'Portmarnock, Dublin, Ireland',      'Dublin',  'https://www.portmarnock.com/',            53.4296, -6.1287, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.1786,-6.1817
  (NULL, 'Powerscourt Golf Club -- East',            'powerscourt-east',    'Enniskerry, Wicklow, Ireland',      'Wicklow', 'https://www.powerscourtgolfclub.com/',    53.1786, -6.1817, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.1872,-6.1861
  (NULL, 'Powerscourt Golf Club -- West',            'powerscourt-west',    'Enniskerry, Wicklow, Ireland',      'Wicklow', 'https://www.powerscourtgolfclub.com/',    53.1872, -6.1861, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.0306,-6.7339
  (NULL, 'Rathsallagh Golf Club',                    'rathsallagh',         'Dunlavin, Wicklow, Ireland',        'Wicklow', 'https://www.rathsallaghcountryclub.com/', 53.0306, -6.7339, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/52.2934,-6.3926
  (NULL, 'Rosslare Golf Club -- Old Course',         'rosslare-old',        'Rosslare, Wexford, Ireland',        'Wexford', 'https://www.rosslaregolf.com/',           52.2934, -6.3926, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.6580,-5.7530
  (NULL, 'Royal Belfast Golf Club',                  'royal-belfast',       'Craigavad, Down, Northern Ireland', 'Down',    'https://www.royalbelfast.com/',            54.658,  -5.753, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/53.7546,-6.2508
  (NULL, 'Seapoint Golf Links',                      'seapoint',            'Termonfeckin, Louth, Ireland',      'Louth',   'https://seapointgolflinks.com/',          53.7546, -6.2508, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.0974,-7.5575
  (NULL, 'Slieve Russell Golf Club',                 'slieve-russell',      'Ballyconnell, Cavan, Ireland',      'Cavan',   'https://www.slieverussell.ie/',           54.0974, -7.5575, now(), false, false, 'Ladies card not published — the men''s numbers are used for everyone'),
  -- https://www.google.com/maps/place/54.2656,-8.6067
  (NULL, 'Strandhill Golf Club',                     'strandhill',          'Strandhill, Sligo, Ireland',        'Sligo',   'https://www.strandhillgolfclub.com/',     54.2656, -8.6067, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/53.1389,-6.5304
  (NULL, 'Tulfarris Golf Club',                      'tulfarris',           'Blessington, Wicklow, Ireland',     'Wicklow', 'https://www.tulfarrisgolfclub.com/',      53.1389, -6.5304, now(), false, true,  NULL),
  -- https://www.google.com/maps/place/53.2416,-7.5203
  (NULL, 'Tullamore Golf Club',                      'tullamore',           'Tullamore, Offaly, Ireland',        'Offaly',  'https://www.tullamoregolfclub.ie/',       53.2416, -7.5203, now(), false, true,  NULL)
ON CONFLICT DO NOTHING;

-- ── North West Golf Club (par 70 men / 72 ladies) ──
-- HOLES MEDIUM: https://www.northwestgolfclub.com/visitor-the-course, https://www.golfpass.com/travel-advisor/courses/19711-north-west-golf-club, https://golftraxx.com/scorecard?course_name=North+West+Golf+Club&fulladdress=Lisfannon,+Fahan,+Buncrana,+IR&zipcode=DONEGAL&static=true
-- Note: Men's par corroborated by the club card, GolfPass and golftraxx; SI from the club's 2025 card (aggregators differ on 3 holes). Ladies card corroborated by the club card and GolfPass.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  3::int, 5::int, 17::int),
  ( 2,      4,      15,      4,       3),
  ( 3,      3,      13,      3,      15),
  ( 4,      4,      11,      4,       7),
  ( 5,      4,       5,      4,       5),
  ( 6,      4,       7,      4,      13),
  ( 7,      4,       1,      4,       1),
  ( 8,      3,       9,      3,       9),
  ( 9,      5,      17,      5,      11),
  (10,      4,       4,      4,       6),
  (11,      4,      10,      4,       2),
  (12,      4,       2,      5,      10),
  (13,      3,      16,      3,      16),
  (14,      4,      14,      4,       4),
  (15,      4,       6,      4,      12),
  (16,      3,      18,      3,      18),
  (17,      4,       8,      4,       8),
  (18,      5,      12,      5,      14)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'north-west' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Portmarnock Resort -- Jameson Golf Links (par 72 men) ──
-- HOLES HIGH: https://www.golfpass.com/travel-advisor/courses/20250-jameson-golf-links, https://18birdies.com/golf-courses/club/7ba5d540-86ac-11e4-8c28-020000005b00/portmarnock-hotel-and-jameson-golf-links
-- Note: Redesigned and reopened 2023 as Jameson Golf Links (par 72); older par-71 Langer-layout data on some aggregators was discarded. Card corroborated by GolfPass and 18Birdies. Ladies omitted (no corroborated ladies card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  8::int, NULL::int, NULL::int),
  ( 2,      4,      12,      NULL,      NULL),
  ( 3,      3,      10,      NULL,      NULL),
  ( 4,      5,       6,      NULL,      NULL),
  ( 5,      4,       4,      NULL,      NULL),
  ( 6,      5,      18,      NULL,      NULL),
  ( 7,      4,       2,      NULL,      NULL),
  ( 8,      4,      14,      NULL,      NULL),
  ( 9,      3,      16,      NULL,      NULL),
  (10,      4,       5,      NULL,      NULL),
  (11,      3,      15,      NULL,      NULL),
  (12,      5,      11,      NULL,      NULL),
  (13,      4,       1,      NULL,      NULL),
  (14,      5,       9,      NULL,      NULL),
  (15,      3,      17,      NULL,      NULL),
  (16,      4,       3,      NULL,      NULL),
  (17,      4,      13,      NULL,      NULL),
  (18,      4,       7,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'portmarnock-jameson' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Powerscourt Golf Club -- East (par 72 men) ──
-- HOLES HIGH: https://powerscourtgolfclub.com/courses/east-course/, https://golfsherpa.co.uk/courses/ireland/powerscourt-golf-club-east, https://www.golfpass.com/travel-advisor/courses/20620-powerscourt-golf-club-east-course
-- Note: Peter McEvoy East course. Men's card agreed by the club card, golfsherpa and GolfPass. Ladies omitted (no corroborated ladies card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  3::int, NULL::int, NULL::int),
  ( 2,      5,      13,      NULL,      NULL),
  ( 3,      3,      17,      NULL,      NULL),
  ( 4,      4,       5,      NULL,      NULL),
  ( 5,      3,       7,      NULL,      NULL),
  ( 6,      5,      11,      NULL,      NULL),
  ( 7,      4,       9,      NULL,      NULL),
  ( 8,      4,       1,      NULL,      NULL),
  ( 9,      4,      15,      NULL,      NULL),
  (10,      4,       6,      NULL,      NULL),
  (11,      4,       8,      NULL,      NULL),
  (12,      5,      16,      NULL,      NULL),
  (13,      3,      10,      NULL,      NULL),
  (14,      4,      14,      NULL,      NULL),
  (15,      4,       4,      NULL,      NULL),
  (16,      3,      18,      NULL,      NULL),
  (17,      5,       2,      NULL,      NULL),
  (18,      4,      12,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'powerscourt-east' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Powerscourt Golf Club -- West (par 72 men) ──
-- HOLES MEDIUM: https://golfsherpa.co.uk/courses/northern-ireland/powerscourt-golf-club-west, https://offcourse.co/courses/scorecard/powerscourt-golf-club/
-- Note: David McLay Kidd West course. Men's card agreed by golfsherpa and offcourse. Ladies omitted (no corroborated ladies card).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int,  5::int, NULL::int, NULL::int),
  ( 2,      3,      13,      NULL,      NULL),
  ( 3,      4,      11,      NULL,      NULL),
  ( 4,      4,       1,      NULL,      NULL),
  ( 5,      4,      15,      NULL,      NULL),
  ( 6,      3,      17,      NULL,      NULL),
  ( 7,      5,       9,      NULL,      NULL),
  ( 8,      4,       3,      NULL,      NULL),
  ( 9,      4,       7,      NULL,      NULL),
  (10,      4,      12,      NULL,      NULL),
  (11,      3,      18,      NULL,      NULL),
  (12,      4,       4,      NULL,      NULL),
  (13,      4,       8,      NULL,      NULL),
  (14,      4,      10,      NULL,      NULL),
  (15,      4,      14,      NULL,      NULL),
  (16,      5,       2,      NULL,      NULL),
  (17,      3,       6,      NULL,      NULL),
  (18,      5,      16,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'powerscourt-west' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Rathsallagh Golf Club (par 72 men / 73 ladies) ──
-- HOLES MEDIUM: https://www.rathsallaghcountryclub.com/score-card.html, https://www.rathsallaghcountryclub.com/cmsFiles/rathsallagh_score_card_1.pdf
-- Note: Christy O'Connor course. Men's and ladies cards from the club's current official scorecard; ladies play the 10th as a par 5 (ladies par 73).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 13::int, 5::int, 15::int),
  ( 2,      4,       2,      4,       1),
  ( 3,      4,      15,      4,      13),
  ( 4,      3,      11,      3,      11),
  ( 5,      4,       9,      4,       9),
  ( 6,      5,       6,      5,       5),
  ( 7,      3,      17,      3,      17),
  ( 8,      4,       4,      4,       7),
  ( 9,      4,       7,      4,       3),
  (10,      4,       1,      5,      10),
  (11,      5,      10,      5,       4),
  (12,      4,      12,      4,      14),
  (13,      3,      18,      3,      12),
  (14,      4,      14,      4,      18),
  (15,      4,       8,      4,       8),
  (16,      5,       5,      5,       6),
  (17,      3,      16,      3,      16),
  (18,      4,       3,      4,       2)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'rathsallagh' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Rosslare Golf Club -- Old Course (par 72 men) ──
-- HOLES HIGH: https://rosslaregolf.com/the-old-course/the-old-course-score-card/, https://www.golfpass.com/travel-advisor/courses/20840-rosslare-golf-links-the-old-course, https://18birdies.com/golf-courses/club/7bae12a0-86ac-11e4-8c28-020000005b00/rosslare-golf-club
-- Note: Men's card corroborated by the official 2025 scorecard, GolfPass and 18Birdies. Ladies SI not corroborated across sources, so ladies are omitted.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  9::int, NULL::int, NULL::int),
  ( 2,      3,      11,      NULL,      NULL),
  ( 3,      5,      13,      NULL,      NULL),
  ( 4,      4,       7,      NULL,      NULL),
  ( 5,      4,       1,      NULL,      NULL),
  ( 6,      4,      15,      NULL,      NULL),
  ( 7,      5,       5,      NULL,      NULL),
  ( 8,      3,      17,      NULL,      NULL),
  ( 9,      4,       3,      NULL,      NULL),
  (10,      3,      10,      NULL,      NULL),
  (11,      4,       2,      NULL,      NULL),
  (12,      5,      16,      NULL,      NULL),
  (13,      4,      14,      NULL,      NULL),
  (14,      3,      12,      NULL,      NULL),
  (15,      4,       6,      NULL,      NULL),
  (16,      4,       8,      NULL,      NULL),
  (17,      4,       4,      NULL,      NULL),
  (18,      5,      18,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'rosslare-old' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Royal Belfast Golf Club (par 70 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/18863-the-royal-belfast-golf-club, https://golfsherpa.co.uk/courses/northern-ireland/the-royal-belfast-golf-club
-- Note: Oldest club in Ireland. Men's par corroborated by four sources; SI by GolfPass and golfsherpa. Ladies omitted (a ladies card appears on only one source).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  7::int, NULL::int, NULL::int),
  ( 2,      4,       3,      NULL,      NULL),
  ( 3,      4,      13,      NULL,      NULL),
  ( 4,      3,      15,      NULL,      NULL),
  ( 5,      5,       9,      NULL,      NULL),
  ( 6,      4,      11,      NULL,      NULL),
  ( 7,      3,      17,      NULL,      NULL),
  ( 8,      4,       5,      NULL,      NULL),
  ( 9,      4,       1,      NULL,      NULL),
  (10,      4,      14,      NULL,      NULL),
  (11,      3,       8,      NULL,      NULL),
  (12,      4,       4,      NULL,      NULL),
  (13,      4,      12,      NULL,      NULL),
  (14,      3,      10,      NULL,      NULL),
  (15,      4,       2,      NULL,      NULL),
  (16,      5,      16,      NULL,      NULL),
  (17,      3,      18,      NULL,      NULL),
  (18,      5,       6,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'royal-belfast' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Seapoint Golf Links (par 72 men) ──
-- HOLES MEDIUM: https://seapointgolflinks.com/the-links/, https://golfsherpa.co.uk/courses/ireland/seapoint-golf-club
-- Note: Men's card agreed by the club's Links page and golfsherpa. Ladies SI conflicts across sources, so ladies are omitted. Official domain is .com.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  7::int, NULL::int, NULL::int),
  ( 2,      3,      15,      NULL,      NULL),
  ( 3,      4,      11,      NULL,      NULL),
  ( 4,      4,       3,      NULL,      NULL),
  ( 5,      4,       1,      NULL,      NULL),
  ( 6,      5,      17,      NULL,      NULL),
  ( 7,      4,       5,      NULL,      NULL),
  ( 8,      5,      13,      NULL,      NULL),
  ( 9,      3,       9,      NULL,      NULL),
  (10,      5,      18,      NULL,      NULL),
  (11,      4,      10,      NULL,      NULL),
  (12,      4,       4,      NULL,      NULL),
  (13,      4,       2,      NULL,      NULL),
  (14,      4,       6,      NULL,      NULL),
  (15,      3,      14,      NULL,      NULL),
  (16,      4,      12,      NULL,      NULL),
  (17,      3,      16,      NULL,      NULL),
  (18,      5,       8,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'seapoint' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Slieve Russell Golf Club (par 72 men) ──
-- HOLES MEDIUM: https://www.golfpass.com/travel-advisor/courses/19397-slieve-russell-hotel-golf-and-country-club, https://18birdies.com/golf-courses/club/7bbd7bf0-86ac-11e4-8c28-020000005b00/slieve-russell-hotel-golf-country-club
-- Note: Men's par corroborated by three sources; SI by GolfPass and 18Birdies (golftraxx SI rejected as outlier). Ladies omitted. Green tee dropped (par mismatch).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int,  7::int, NULL::int, NULL::int),
  ( 2,      4,       1,      NULL,      NULL),
  ( 3,      4,       4,      NULL,      NULL),
  ( 4,      3,      15,      NULL,      NULL),
  ( 5,      4,       3,      NULL,      NULL),
  ( 6,      5,      18,      NULL,      NULL),
  ( 7,      3,       8,      NULL,      NULL),
  ( 8,      4,      12,      NULL,      NULL),
  ( 9,      5,      17,      NULL,      NULL),
  (10,      4,       6,      NULL,      NULL),
  (11,      3,      11,      NULL,      NULL),
  (12,      4,       2,      NULL,      NULL),
  (13,      5,      14,      NULL,      NULL),
  (14,      4,      16,      NULL,      NULL),
  (15,      4,       5,      NULL,      NULL),
  (16,      3,      13,      NULL,      NULL),
  (17,      4,       9,      NULL,      NULL),
  (18,      5,      10,      NULL,      NULL)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'slieve-russell' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Strandhill Golf Club (par 70 men / 72 ladies) ──
-- HOLES MEDIUM: https://strandhillgolfclub.com/wp-content/uploads/2026/03/Strandhill-Golf-Club-Scorecard-2024-back_A5_compressed.pdf, https://www.gogolfing.ie/golf-course.php?id_club=348
-- Note: Men's par matches the official card and gogolfing; SI from the club card (gogolfing agrees 16/18). Ladies card from the official card; ladies play the 16th and 18th as par 5s.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 10::int, 5::int,  8::int),
  ( 2,      3,      12,      3,      18),
  ( 3,      4,       8,      4,      12),
  ( 4,      4,       6,      4,       2),
  ( 5,      5,      16,      5,      10),
  ( 6,      4,       2,      4,       4),
  ( 7,      4,       4,      4,       6),
  ( 8,      4,      14,      4,      14),
  ( 9,      3,      18,      3,      16),
  (10,      4,      11,      4,       7),
  (11,      4,      15,      4,      11),
  (12,      4,       7,      4,       1),
  (13,      4,       9,      4,       5),
  (14,      3,      17,      3,      17),
  (15,      4,       3,      4,       3),
  (16,      4,       5,      5,      15),
  (17,      3,      13,      3,      13),
  (18,      4,       1,      5,       9)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'strandhill' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Tulfarris Golf Club (par 72 men / 72 ladies) ──
-- HOLES HIGH: https://www.tulfarrisgolfclub.com/scorecard/, https://tulfarrisgolfclub.com/wp-content/uploads/2026/04/TGC-Scorecard.webp
-- Note: Par, SI and tee ratings from the club's current scorecard (2026) and per-tee handicap sheets; slopes cross-checked. Ladies card from the Red column (ladies par 72).
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 5::int, 12::int, 5::int,  2::int),
  ( 2,      3,      16,      3,       8),
  ( 3,      4,       4,      4,      14),
  ( 4,      4,       2,      4,       6),
  ( 5,      4,      14,      4,      16),
  ( 6,      3,      10,      3,      18),
  ( 7,      4,      18,      4,      10),
  ( 8,      4,       8,      4,       4),
  ( 9,      5,       6,      5,      12),
  (10,      4,       1,      4,       3),
  (11,      3,      17,      3,      17),
  (12,      4,       7,      4,      11),
  (13,      5,      15,      5,       9),
  (14,      4,       9,      4,      13),
  (15,      5,      13,      5,       5),
  (16,      3,      11,      3,      15),
  (17,      4,       5,      4,       1),
  (18,      4,       3,      4,       7)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'tulfarris' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

-- ── Tullamore Golf Club (par 70 men / 72 ladies) ──
-- HOLES MEDIUM: https://www.tullamoregolfclub.ie/scorecard/, https://offcourse.co/courses/scorecard/tullamore-golf-club
-- Note: Men's card from the club scorecard and offcourse; ladies card corroborated by the club card and GolfPass. Ladies play the 14th and 18th as par 5s.
INSERT INTO holes (course_id, hole_number, par, stroke_index, par_ladies, stroke_index_ladies)
SELECT c.id, v.n, v.p, v.s, v.pl, v.sl
FROM (VALUES
  ( 1::int, 4::int, 12::int, 4::int,  7::int),
  ( 2,      3,      14,      3,      17),
  ( 3,      4,       4,      4,       9),
  ( 4,      5,       9,      5,       3),
  ( 5,      4,       2,      4,       1),
  ( 6,      3,       8,      3,      11),
  ( 7,      5,      18,      5,       5),
  ( 8,      4,      15,      4,      15),
  ( 9,      3,      16,      3,      13),
  (10,      4,      10,      4,       6),
  (11,      4,      17,      4,      10),
  (12,      3,       7,      3,      16),
  (13,      4,       6,      4,      18),
  (14,      4,       1,      5,       2),
  (15,      5,      11,      5,       8),
  (16,      4,       3,      4,       4),
  (17,      3,      13,      3,      12),
  (18,      4,       5,      5,      14)
) AS v(n, p, s, pl, sl)
JOIN courses c ON c.slug = 'tullamore' AND c.trip_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO tees (course_id, name, gender, par, course_rating, slope)
SELECT c.id, spec.tee_name, spec.gender, spec.par::integer,
       spec.course_rating::numeric, spec.slope::integer
FROM (VALUES
  -- ── North West Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/19711-north-west-golf-club, https://www.golfshake.com/course/view/15653/North_West_Golf_Club.html
  ('north-west',          'White',  'M', 70, 69.9, 116),
  ('north-west',          'Yellow', 'M', 70, 69.2, 114),
  ('north-west',          'Green',  'M', 70, 68.5, 113),
  ('north-west',          'Red',    'F', 72, 73.4, 130),

  -- ── Portmarnock Resort -- Jameson Golf Links ──
  -- TEES HIGH: https://www.golfpass.com/travel-advisor/courses/20250-jameson-golf-links, https://18birdies.com/golf-courses/club/7ba5d540-86ac-11e4-8c28-020000005b00/portmarnock-hotel-and-jameson-golf-links
  ('portmarnock-jameson', 'Blue',   'M', 72, 75.8, 133),
  ('portmarnock-jameson', 'White',  'M', 72, 73.5, 130),
  ('portmarnock-jameson', 'Green',  'M', 72, 71.1, 125),
  ('portmarnock-jameson', 'Red',    'M', 72, 67.3, 118),
  ('portmarnock-jameson', 'White',  'F', 72, 77.8, 138),
  ('portmarnock-jameson', 'Green',  'F', 72, 77.1, 137),
  ('portmarnock-jameson', 'Red',    'F', 72, 72.7, 126),

  -- ── Powerscourt Golf Club -- East ──
  -- TEES MEDIUM: https://golfsherpa.co.uk/courses/ireland/powerscourt-golf-club-east, https://www.golfpass.com/travel-advisor/courses/20620-powerscourt-golf-club-east-course
  ('powerscourt-east',    'Blue',   'M', 72, 74.3, 134),
  ('powerscourt-east',    'White',  'M', 72, 72.1, 130),
  ('powerscourt-east',    'Green',  'M', 72, 70.7, 127),
  ('powerscourt-east',    'Red',    'F', 72, 73.9, 128),

  -- ── Powerscourt Golf Club -- West ──
  -- TEES MEDIUM: https://golfsherpa.co.uk/courses/northern-ireland/powerscourt-golf-club-west
  ('powerscourt-west',    'Blue',   'M', 72, 74.2, 134),
  ('powerscourt-west',    'White',  'M', 72, 72.1, 129),
  ('powerscourt-west',    'Green',  'M', 72, 69.7, 125),
  ('powerscourt-west',    'Red',    'F', 72, 72.5, 129),

  -- ── Rathsallagh Golf Club ──
  -- TEES MEDIUM: https://www.rathsallaghcountryclub.com/cmsFiles/rathsallagh_score_card_1.pdf
  ('rathsallagh',         'Black',  'M', 72, 74.0, 132),
  ('rathsallagh',         'Blue',   'M', 72, 71.7, 127),
  ('rathsallagh',         'White',  'M', 72, 70.3, 125),
  ('rathsallagh',         'Red',    'F', 73, 72.2, 122),

  -- ── Rosslare Golf Club -- Old Course ──
  -- TEES HIGH: https://rosslaregolf.com/the-old-course/the-old-course-score-card/, https://18birdies.com/golf-courses/club/7bae12a0-86ac-11e4-8c28-020000005b00/rosslare-golf-club
  ('rosslare-old',        'Blue',   'M', 72, 72.8, 131),
  ('rosslare-old',        'White',  'M', 72, 72.0, 127),
  ('rosslare-old',        'Green',  'M', 72, 70.6, 124),

  -- ── Royal Belfast Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/18863-the-royal-belfast-golf-club
  ('royal-belfast',       'Blue',   'M', 70, 70.8, 125),
  ('royal-belfast',       'White',  'M', 70, 70.2, 124),
  ('royal-belfast',       'Green',  'M', 70, 69.1, 117),

  -- ── Seapoint Golf Links ──
  -- TEES MEDIUM: https://golfsherpa.co.uk/courses/ireland/seapoint-golf-club
  ('seapoint',            'Blue',   'M', 72, 74.5, 131),
  ('seapoint',            'White',  'M', 72, 72.9, 128),
  ('seapoint',            'Green',  'M', 72, 71.4, 127),
  ('seapoint',            'Red',    'M', 72, 68.2, 121),
  ('seapoint',            'Green',  'F', 72, 77.6, 136),
  ('seapoint',            'Red',    'F', 72, 73.2, 128),

  -- ── Slieve Russell Golf Club ──
  -- TEES MEDIUM: https://www.golfpass.com/travel-advisor/courses/19397-slieve-russell-hotel-golf-and-country-club
  ('slieve-russell',      'Blue',   'M', 72, 75.0, 130),
  ('slieve-russell',      'White',  'M', 72, 72.8, 126),
  ('slieve-russell',      'Red',    'F', 72, 73.3, 135),

  -- ── Strandhill Golf Club ──
  -- TEES MEDIUM: https://strandhillgolfclub.com/wp-content/uploads/2026/03/Strandhill-Golf-Club-Scorecard-2024-back_A5_compressed.pdf, https://www.gogolfing.ie/golf-course.php?id_club=348
  ('strandhill',          'White',  'M', 70, 70.7, 125),
  ('strandhill',          'Green',  'M', 70, 68.7, 119),
  ('strandhill',          'Red',    'F', 72, 71.7, 126),

  -- ── Tulfarris Golf Club ──
  -- TEES HIGH: https://tulfarrisgolfclub.com/wp-content/uploads/2025/06/Men-Blue-Handicap-Sheet-.pdf, https://tulfarrisgolfclub.com/wp-content/uploads/2025/06/Mens-White-Handicap-Sheet.pdf, https://tulfarrisgolfclub.com/wp-content/uploads/2025/06/Mens-Green-Handicap-Sheet.pdf
  ('tulfarris',           'Blue',   'M', 72, 75.4, 136),
  ('tulfarris',           'White',  'M', 72, 73.2, 132),
  ('tulfarris',           'Green',  'M', 72, 71.8, 129),
  ('tulfarris',           'Red',    'M', 72, 67.2, 117),

  -- ── Tullamore Golf Club ──
  -- TEES MEDIUM: https://www.tullamoregolfclub.ie/wp-content/uploads/2024/05/Tullamore-Golf-Club-Handicap-Tables-May-2024-White.pdf
  ('tullamore',           'Blue',   'M', 70, 71.8, 131),
  ('tullamore',           'White',  'M', 70, 70.9, 129),
  ('tullamore',           'Red',    'F', 72, 72.7, 129)
) AS spec(slug, tee_name, gender, par, course_rating, slope)
JOIN courses c ON c.slug = spec.slug AND c.trip_id IS NULL
ON CONFLICT ON CONSTRAINT uq_tees_course_name_gender DO NOTHING;

COMMIT;

-- ── Did it land? ──────────────────────────────────────────
-- Run this after the COMMIT above. Every course below should come back with
-- its holes and tees. /admin/courses says the same thing with badges.
--
-- select c.slug, c.name, c.county, c.card_verified,
--        (select count(*) from holes h where h.course_id = c.id) as holes,
--        (select count(*) from tees  t where t.course_id = c.id) as tees
-- from courses c
-- where c.trip_id is null
--   and c.slug in ('north-west', 'portmarnock-jameson', 'powerscourt-east', 'powerscourt-west', 'rathsallagh', 'rosslare-old', 'royal-belfast', 'seapoint', 'slieve-russell', 'strandhill', 'tulfarris', 'tullamore')
-- order by c.name;
